WIP: Adding opt-in common test for spellchecking markdown files
PowerShell/DscResource.Tests pull request #279
Opened 2018-08-10 06:28 UTC by johlju

- Adding opt-in common test for spellchecking markdown files. Opt-in by
  adding "Common Tests - Spellcheck Markdown Files" in the file
  .MetaTestOptIn.json (issue #211).

Fixes #211

2018-08-10 06:39 UTC, johlju commented
Tested OK here:
CertificateDsc (Not opt-in): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.40.0#L460
CertificateDsc (Opt-in and failing test): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.39.0#L465

2018-08-10 06:46 UTC, johlju commented
Test **FAILED** here:
CertificateDsc (opt-in, and passing tests): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.45.0#L460

This problem has been reported here: https://github.com/Jason3S/cspell/issues/61

It is using this [cSpell](https://www.npmjs.com/package/cspell) configuration file (`.vscode/cSpell.json`):
```json
{
    "ignorePaths": [
        ".git/*",
        ".vscode/*",
        "DSCResource.Tests/*",
        "DscResource.Tests/*"
    ],
    "language": "en",
    "dictionaries": [
        "powershell"
    ],
    "words": [
        "FIPS",
        "MSFT",
        "HQRM",
        "markdownlint",
        "Chocolatey",
        "codecov"

    ],
    "ignoreRegExpList": [
        "\\.gitignore",
        "\\.gitattributes",
        "AppVeyor",
        "opencode@microsoft.com"
    ]
}
```

The key `ignorePaths`, that is because 'DscResource.Tests` are written twice (locally when cloned it has upper-case in 'Dsc', issue https://github.com/PowerShell/DscResources/issues/431).

The key `dictionaries` might not be necessary for this test to pass, but good to have when using the VSCode extension [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

This configuration file, and how it can be used by the test and VS Code should be documented before merge.

2018-08-10 15:48 UTC, johlju commented
**Tested OK**:
CertificateDsc (Not opt-in): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.46.0#L460
CertificateDsc (Opt-in and failing test): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.47.0#L460
CertificateDsc (opt-in, and passing tests): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.48.0#L460

2018-08-15 07:09 UTC, johlju commented
Need help review this PR. I anyone wants to review this PR, or any other PR, you are more than welcome! Love to have more people helping out with reviews!

2018-08-16 08:42 UTC, johlju commented
I will rebase once the other two PR's are through, because they made changes in sections in markdown that was moved in this PR. But anyone, please start the review anyway.

2018-08-17 07:41 UTC, PlagueHO reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/279)* status: all files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[Meta.Tests.ps1, line 1085 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5ltFa6HeAiHBDfvNX:-LK5ltFb-pQd1xqUUgMo:boz49gf) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/Meta.Tests.ps1#L1085)):*
> ```PowerShell
>         It 'Should not have spelling errors in any markdown files' -Skip:(!$optIn) {
>             $spellcheckSettingsFilePath = Join-Path -Path $repoRootPath -ChildPath '.vscode\cSpell.json'
>             if (Test-Path -Path $spellcheckSettingsFilePath)
> ```

Can add a blank line above here?
___
*[Meta.Tests.ps1, line 1150 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5mCLPD2B2amWLcPGz:-LK5mCLPD2B2amWLcPH-:b-6rl2ym) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/Meta.Tests.ps1#L1150)):*
> ```PowerShell
>         if (Test-Path $errorFileName)
>         {
>             Remove-Item -Path $errorFileName -Force
> ```

FYI, Could assign to $null so that we don't end up outputting result to output stream.
___
*[README.md, line 123 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5msCdDcdNV3pfGqFu:-LK5msCdDcdNV3pfGqFv:b7e0s8e) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L123)):*
> ```Markdown
> #### Common Tests - Spellcheck Markdown Files
> 
> When opt-in for this test, if there are any spelling errors in markdown files,
> ```

When opt-in for -> When opt-in to
___
*[README.md, line 127 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5myTk86DJdKpfiWh5:-LK5myTk86DJdKpfiWh6:b-gglqta) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L127)):*
> ```Markdown
> 
> >**Note:** The spell checker is case-insensitive, so the words 'AppVeyor' and
> >'appveyor' is equal and both allowed.
> ```

is equal and both allowed. -> are equal and both are allowed.
___
*[README.md, line 130 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5n2jpD2w9Vo-bi_zV:-LK5n2jpD2w9Vo-bi_zW:b-nikxdz) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L130)):*
> ```Markdown
> 
> If the spell checker ([cSpell](https://www.npmjs.com/package/cspell)) does not
> recognize the word, but the word are correct, or maybe there are a specific phrase
> ```

Might read better as:

```text
If the spell checker ([cSpell](https://www.npmjs.com/package/cspell)) does not
recognize the word, but the word is correct or a specific phrase is not recognized
but should be allowed, then it is possible to add these to a dictionary or tell it to
ignore the word of phrases. This is done by adding a `\.vscode\cSpell.json` in
the repository.
```
___
*[README.md, line 134 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5nkys8oEhuO4zZuNn:-LK5nkys8oEhuO4zZuNo:b-2dnzq3) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L134)):*
> ```Markdown
> tell it to ignore words or phrases.
> 
> By adding a file `\.vscode\cSpell.json` in the repository, the spell checker
> ```

This line could be removed if using the text above.
___
*[README.md, line 137 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5nvH_09okIjd4tPLy:-LK5nvHa4pb_BF1d8TSP:bs8n1jh) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L137)):*
> ```Markdown
> will follow the settings in this file.
> 
> The simplest form of the file `\.vscode\cSpell.json` is this (see
> ```

The following JSON is the simplest form of the file `\.vscode\cSpell.json` (see [cSpell](https://www.npmjs.com/package/cspell) for more settings).
___
*[README.md, line 174 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5oCCY1UaNjKY8sP91:-LK5oCCY1UaNjKY8sP92:b645tvg) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L174)):*
> ```
> The key `ignoreRegExpList` is better to use to ignore phrases or combination of
> ```

The key `ignoreRegExpList` is used to ignore phrases or combinations of words, such as `AppVeyor`, which will be detected as two different words since it consists of two words starting with upper-case letters.
___
*[README.md, line 177 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5omC4EtESlwi8E2Tg:-LK5omC4EtESlwi8E2Th:b-k0qnak) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L177)):*
> ```Markdown
> words, like 'AppVeyor', it will detect that word as two different words, since
> it consist of two words with upper-case letter.
> So for it to ignore 'AppVeyor', as we know it's correct, we can add a regular
> ```

To configure cSpell to ignore `AppVeyor`, then we can add a regular expression, in this case `AppVeyor`. This will cause cSpell to ignore part of the text that matches the regular expression.


<!-- Sent from Reviewable.io -->

2018-08-17 07:57 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/279)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[Meta.Tests.ps1, line 1085 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5ltFa6HeAiHBDfvNX:-LK5sUGp8xHNqZgLep3g:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/Meta.Tests.ps1#L1085)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can add a blank line above here?
</blockquote></details>

Done.
___
*[README.md, line 123 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5msCdDcdNV3pfGqFu:-LK5sWWJ8qSSfQ_B_5MK:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L123)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

When opt-in for -> When opt-in to
</blockquote></details>

Done.
___
*[README.md, line 127 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5myTk86DJdKpfiWh5:-LK5sZTJ9t6tDkO5B0pY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L127)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

is equal and both allowed. -> are equal and both are allowed.
</blockquote></details>

Done.
___
*[README.md, line 130 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5n2jpD2w9Vo-bi_zV:-LK5sbDY6vN5Ty6o6I4j:b-nnbhjx) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L130)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Might read better as:

```text
If the spell checker ([cSpell](https://www.npmjs.com/package/cspell)) does not
recognize the word, but the word is correct or a specific phrase is not recognized
but should be allowed, then it is possible to add these to a dictionary or tell it to
ignore the word of phrases. This is done by adding a `\.vscode\cSpell.json` in
the repository.
```

</blockquote></details>

Done. Thank you for the updated text in the review comments! Much better now! :smile: 
___
*[README.md, line 134 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5nkys8oEhuO4zZuNn:-LK5sfMrDkBxSDnh1J_U:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L134)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This line could be removed if using the text above.
</blockquote></details>

Done.
___
*[README.md, line 137 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5nvH_09okIjd4tPLy:-LK5shXYBArTtnPNi9U9:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L137)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The following JSON is the simplest form of the file `\.vscode\cSpell.json` (see [cSpell](https://www.npmjs.com/package/cspell) for more settings).
</blockquote></details>

Done.
___
*[README.md, line 174 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5oCCY1UaNjKY8sP91:-LK5snCF8DMcJUaGkLKZ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L174)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> The key `ignoreRegExpList` is better to use to ignore phrases or combination of
> ```

The key `ignoreRegExpList` is used to ignore phrases or combinations of words, such as `AppVeyor`, which will be detected as two different words since it consists of two words starting with upper-case letters.
</blockquote></details>

Done.
___
*[README.md, line 177 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5omC4EtESlwi8E2Tg:-LK5so-W6_aAkKeUzi1B:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L177)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

To configure cSpell to ignore `AppVeyor`, then we can add a regular expression, in this case `AppVeyor`. This will cause cSpell to ignore part of the text that matches the regular expression.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-29 04:44 UTC, johlju commented
@PlagueHO when you have a chance, can you see if I got all the review comments, and there are no new comments? 🙂

2018-08-29 07:14 UTC, PlagueHO requested changes
Almost perfect @johlju - but I had one mistake in my suggested text that needs to be corrected.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/279#-:-LL3X3-gEWaRkJm2KxRb:be2ovaa)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[README.md, line 130 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5n2jpD2w9Vo-bi_zV:-LL3Wp0F6Pt-1Tj8t86h:b-hfdpsz) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L130)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Thank you for the updated text in the review comments! Much better now! :smile: 
</blockquote></details>

Doh - slight mistake (from my text): word of phrases -> word or phrases


<!-- Sent from Reviewable.io -->

2018-08-29 07:56 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/279)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[README.md, line 130 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/279#-LK5n2jpD2w9Vo-bi_zV:-LL3fguWE32HFbT5fvom:b-kdwq6t) ([raw file](https://github.com/powershell/dscresource.tests/blob/223ebdaacf0cf74d0448bfaaad82581b19477eaf/README.md#L130)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doh - slight mistake (from my text): word of phrases -> word or phrases
</blockquote></details>

Done. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2018-08-31 06:34 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/279#-:-LLDgBb852xHR3JkNx3Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-31 06:34 UTC, merged