Added RequiredVersion for PSPKI
PowerShell/DscResource.Tests pull request #304
Opened 2018-10-17 13:57 UTC by ykuijs

#### Pull Request (PR) description
The version of PSPKI that was released on Oct 15th has an issue in New-SelfsignedCertificateEx, which is blocking PRs from being successfully tested: https://github.com/Crypt32/PSPKI/issues/56

This PR forces the use of v3.3.0.0, in which the tests work fine.

Can this PR please be reviewed and merged soon, since this issue is blocking all PRs in SharePointDsc

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Documentation added/updated in README.md.
- [X] Comment-based help added/updated for all new/changed functions.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Unit tests added/updated.
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2018-10-17 16:49 UTC, johlju reviewed
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/304#-LP1vVWeB08GUShs3U95:-LP1vVWeB08GUShs3U96:bs9y3e9) ([raw file](https://github.com/powershell/dscresource.tests/blob/95560a4fb1b59b8cf9ea9bbded24c54f95dcc137/CHANGELOG.md#L9)):*
> ```Markdown
>   ([issue #219](https://github.com/PowerShell/DscResource.Tests/issues/219)).
> - Added a RequiredVersion for PSPKI in TestHelper because of a critical issue
>   in the recently released version of that module
> ```

Add a full stop (.) at the end of the phrase.


<!-- Sent from Reviewable.io -->

2018-10-17 16:57 UTC, ykuijs reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/304#-LP1vVWeB08GUShs3U95:-LP1xOH49DDXCf8E5gpS:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/95560a4fb1b59b8cf9ea9bbded24c54f95dcc137/CHANGELOG.md#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Add a full stop (.) at the end of the phrase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-17 16:58 UTC, johlju reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

@PlagueHO can you merge this one when you think it's ready?

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304#-:-LP1xjovC0YC6ExDQ85H:b-ytf4bp)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-10-17 20:38 UTC, PlagueHO requested changes
Just one minor tweak @ykuijs - then I can merge.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304#-:-LP2jvBA4q7RcWB13bt2:btyjkno)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[CHANGELOG.md, line 9 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/304#-LP2jg1D93uHVPgn1kNP:-LP2jg1D93uHVPgn1kNQ:b-cx3amf) ([raw file](https://github.com/powershell/dscresource.tests/blob/72422605a3955b7d19245b6156c29bd9e4b579ae/CHANGELOG.md#L9)):*
> ```Markdown
>   ([issue #219](https://github.com/PowerShell/DscResource.Tests/issues/219)).
> - Added a RequiredVersion for PSPKI in TestHelper because of a critical issue
>   in the recently released version of that module.
> ```

Could you add the version number of the module that was released in here and mention the one that works (3.3.0.0)?


<!-- Sent from Reviewable.io -->

2018-10-18 07:37 UTC, ykuijs reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju and @PlagueHO)

___
*[CHANGELOG.md, line 9 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/304#-LP2jg1D93uHVPgn1kNP:-LP55vTUDUpTJ0qsge_P:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/72422605a3955b7d19245b6156c29bd9e4b579ae/CHANGELOG.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add the version number of the module that was released in here and mention the one that works (3.3.0.0)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-18 08:04 UTC, PlagueHO approved these changes
Thanks @ykuijs - awesome stuff! Thank you

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/304#-:-LP5C2whEcnIWXWktPzb:b-t5zpuz)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-10-18 08:05 UTC, merged

2018-10-18 08:10 UTC, ykuijs commented
Thanks for this merge! The PRs in SharePointDsc can now be successfully resumed!

2018-10-19 08:57 UTC, PlagueHO commented
Thanks for sorting this @ykuijs !!!