New WikiPages Function: Publish-WikiContent
PowerShell/DscResource.Tests pull request #324
Opened 2019-06-09 20:09 UTC by X-Guardian

#### Pull Request (PR) description

This PR adds the following:

1. A new WikiPages function `Publish-WikiContent` which publishes the contents of a DSC Resource Module Wiki Content artifact from an AppVeyor job to the relevant GitHub Wiki repository.
2. An additional `PublishWikiContent` option to the `Invoke-AppVeyorDeployTask` `OptIn` parameter which if set, will call the `Publish-WikiContent` function with the relevant parameters.

To enable the function, the following process needs to be followed:

1. Obtain a GitHub Personal Access Token with `repo/public_repo` permissions for a user that has at least `Collaborator` access to the relevant DSC Module GitHub repositiry.
2. Make the following modifications to the `appveyor.yml` file of the relevant DSC Module GitHub repository:
    1. Add the Github Personal Access Token as a [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) called `github_access_token` to the `environment` section.
    2. Add the `PublishWikiContent` OptIn property to the `Invoke-AppVeyorDeployTask` function call in the `deploy_script` section as follows:

```
deploy_script:
  - ps: |
        Invoke-AppVeyorDeployTask -Optin 'PublishExample', 'PublishWikiContent'
```

#### Notes

- The GitHub Wiki needs to be initialised on a repository before this function is run.
- Currently Wiki content files are only added or updated by the function, not deleted.
- A `username` and `email` for the Git commit needs to be specified as parameters to the `Publish-WikiContent` function. These currently default to `AppVeyor` and `appveyor@microsoft.com`, but can be changed if required.

As an example, this fork of the [xActiveDirectory](https://github.com/X-Guardian/xActiveDirectory) repository has the `Publish-WikiContent` enabled, with this example [Pull Request](https://github.com/X-Guardian/xActiveDirectory/pull/14) and [AppVeyor build](https://ci.appveyor.com/project/X-Guardian/xactivedirectory/builds/25153954) deploying the Wiki.

#### This Pull Request (PR) fixes the following issues

- Fixes #142 

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-06-10 07:19 UTC, X-Guardian commented
I haven't added instructions to the README yet. I'll do that once everyone has reviewed the implementation details.

2019-06-10 08:45 UTC, PlagueHO commented
Awesome stuff @X-Guardian! I haven't had a chance to do a full review on it, but a quick suggestion is to separate the strings into a localization file as per other modules. Will be great to get this in.

2019-06-10 09:18 UTC, X-Guardian commented
Will do @PlagueHO.

2019-06-10 17:12 UTC, johlju reviewed
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 17 unresolved discussions (waiting on @X-Guardian)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1E5ts15x0bmQ04zdz:-Lh1E5ts15x0bmQ04ze-:b7hf3ox) (no related file):*
The text in the PR description would be great to add as a new section under https://github.com/PowerShell/DscResource.Tests/blob/dev/README.md#deploy

---
___
*[AppVeyor.psm1, line 1244 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1ENkrCwqQpCQABhr6:-Lh1ENkrCwqQpCQABhr7:bm3jn8t) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/AppVeyor.psm1#L1244)):*
> ```
> $OptIn = @(
> ```

My thought was that the default is to opt-in to all deploy steps unless the repo has specifically opt-in to specific. If we are gonna continue with that approach then we should add this new deploy option to the default values to. @PlagueHO what is your your thoughts bout this?
___
*[AppVeyor.psm1, line 1291 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1F2bi4pT3PO39f7YM:-Lh1F2bi4pT3PO39f7YN:b-f44mgo) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/AppVeyor.psm1#L1291)):*
> ```
> if ($OptIn ...
> ```

Should we add an else block here too as the previous deploy step? I think it is good information if  it is needed to debug the pipeline.

```powershell
else
{
    Write-Info -Message 'Skip publish wiki content to the repository Wiki. Either not opt-in, or building on the wrong branch.'
}
```
___
*[xActiveDirectory.wiki, line 1 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1DahS80Ny0Itrc1Ci:-Lh1DahS80Ny0Itrc1Cj:b-iyfuvc) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/xActiveDirectory.wiki#L1)):*
> ```
> Subproject commit 4ed275286a3aba01f13eb7017a71bd93b2318eb5
> ```

Not sure this should be part of the PR?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 361 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Fle6DwlgqeIo1fCF:-Lh1Fle6DwlgqeIo1fCG:bprhlus) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L361)):*
> ```
> "appveyor@microsoft.com"
> ```

We should use single-quotes where applicable.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 365 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1FpCxEu63k_IsQ_6o:-Lh1FpCy8StkcJaXnp7B:b-6v86l9) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L365)):*
> ```
> "AppVeyor"
> ```

We should use single-quotes where applicable.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 370 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1FqjUALbnczig_Ivt:-Lh1FqjUALbnczig_Ivu:b-b9mnv3) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L370)):*
> ```
> data localizedData
> ```

As per comment by @PlagueHO, we should separate these localization strings to a string resource file.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 401 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1GMBP3WJg2HxCj0uf:-Lh1GMBP3WJg2HxCj0ug:bbltwwe) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L401)):*
> ```PowerShell
>     do
>     {
>       $name = [System.IO.Path]::GetRandomFileName()
> ```

This row and the next seems not to be indented correctly.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 402 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1GVdP8A0BO3UMywJy:-Lh1GVdP8A0BO3UMywJz:b-uubo6s) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L402)):*
> ```
> New-Item
> ```

Non-blocking. We do not need to use `-Force` on this?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 408 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1HCvvCnan7H2qqRNP:-Lh1HCvvCnan7H2qqRNQ:bqrhm9s) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L408)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     Invoke-Git config --global user.email $GitUserEmail
>     Invoke-Git config --global user.name $GitUserName
>     Invoke-Git config --global core.autocrlf true
>     Invoke-Git config --global credential.helper store
> ```
</details>


Can we set these after the repo has been cloned and we moved into the repo folder so we can use `--local` instead? Then we don't mess with other potential deploy step if we just change for the specific wiki repo.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 411 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Iex7CPZPPovE6Gx-:-Lh1Iex7CPZPPovE6Gx0:b-w9acgr) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L411)):*
> ```
> Add-Content "$HOME\.git-credentials" "https://$($GitUserName):$($GithubAccessToken)@github.com`n"
> ```

Instead of using this file, would it be possible to pass the token in the `git` calls, or just add the credentials to the wiki repo scope? My thought is to not have a file with the token on the build worker (even if it is for a time it is building).
If we need this file should remove it once we have deployed?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 423 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1JtLW1kuFEyJswf17:-Lh1JtLW1kuFEyJswf18:b-ioo9nm) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L423)):*
> ```
> catch {
> ```

Open-brace should be on its own row.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 424 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1K-5WBV8e26IOOhfI:-Lh1K-5WBV8e26IOOhfJ:b-hgtmwt) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L424)):*
> ```
> Switch
> ```

`switch` (lower-case 's')
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 428 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1K99b3OlQ8wqiOF3H:-Lh1K99b3OlQ8wqiOF3I:b-fglo57) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L428)):*
> ```
> Throw
> ```

`throw` (lower-case 't'). Throughout the code.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 437 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1KTkPC4Is5eYHCRom:-Lh1KTkPC4Is5eYHCRon:b-fm0k6v) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L437)):*
> ```
> Where-Object fileName -like "$ResourceModuleName_*_wikicontent.zip"
> ```

We usually write these as

```powershell
Where-Object -FilterScript { fileName -like "$ResourceModuleName_*_wikicontent.zip" }
```
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 449 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1L9UrDbofLt_wgdZt:-Lh1L9UrDbofLt_wgdZu:b-50uugp) ([raw file] [...]

2019-06-10 17:12 UTC, johlju commented
@X-Guardian Awesome work on this! 😃

2019-06-10 20:14 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 17 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

___
*[AppVeyor.psm1, line 1244 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1ENkrCwqQpCQABhr6:-Lh1mm1p8BpUWkPmcYG7:bkbkpql) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/AppVeyor.psm1#L1244)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $OptIn = @(
> ```

My thought was that the default is to opt-in to all deploy steps unless the repo has specifically opt-in to specific. If we are gonna continue with that approach then we should add this new deploy option to the default values to. @PlagueHO what is your your thoughts bout this?
</blockquote></details>

The `github_access_token` needs to be added to the `appveyor.yml` for each DSC Module repo before the publishing is going to work, as well as the Wiki site being initialised with a home page, so I would have this as opt-in so a managed roll-out can be done.
___
*[AppVeyor.psm1, line 1291 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1F2bi4pT3PO39f7YM:-Lh1nTOR6CD4qc2I9Gzu:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/AppVeyor.psm1#L1291)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($OptIn ...
> ```

Should we add an else block here too as the previous deploy step? I think it is good information if  it is needed to debug the pipeline.

```powershell
else
{
    Write-Info -Message 'Skip publish wiki content to the repository Wiki. Either not opt-in, or building on the wrong branch.'
}
```
</blockquote></details>

Done.
___
*[xActiveDirectory.wiki, line 1 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1DahS80Ny0Itrc1Ci:-Lh1pOeG5MkLBytiE6zO:b-my8ygi) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/xActiveDirectory.wiki#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Subproject commit 4ed275286a3aba01f13eb7017a71bd93b2318eb5
> ```

Not sure this should be part of the PR?
</blockquote></details>

Whoops, removed!
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 361 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Fle6DwlgqeIo1fCF:-Lh1panY5VPVhVyOwTEa:bk7ulnq) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L361)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "appveyor@microsoft.com"
> ```

We should use single-quotes where applicable.
</blockquote></details>

Done.

These are just place holders. What user details do you want on the commits?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 365 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1FpCxEu63k_IsQ_6o:-Lh1ppN49ChE3qV8YSwb:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L365)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "AppVeyor"
> ```

We should use single-quotes where applicable.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 370 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1FqjUALbnczig_Ivt:-Lh1qxJv1Yz-PJ0yuv1R:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L370)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> data localizedData
> ```

As per comment by @PlagueHO, we should separate these localization strings to a string resource file.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 401 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1GMBP3WJg2HxCj0uf:-Lh1r5jD-lcn3YmuzNQA:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L401)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This row and the next seems not to be indented correctly.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 402 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1GVdP8A0BO3UMywJy:-Lh1rGLJ56Eart1NqAl_:b7576wy) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L402)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> New-Item
> ```

Non-blocking. We do not need to use `-Force` on this?
</blockquote></details>

This is template code that copes with race conditions of the temp directory being created by another process between the `GetRandomFileName` call and the `New-Item`. Adding `force` would suggest that a race condition had occurred, and we would then be overwriting the other directory. Better to go round the loop again and pick another random name. (not that we are likely to hit this scenario in a container, but anyway.)
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 408 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1HCvvCnan7H2qqRNP:-Lh20Upo1B6JhWVa4rT9:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L408)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     Invoke-Git config --global user.email $GitUserEmail
>     Invoke-Git config --global user.name $GitUserName
>     Invoke-Git config --global core.autocrlf true
>     Invoke-Git config --global credential.helper store
> ```

Can we set these after the repo has been cloned and we moved into the repo folder so we can use `--local` instead? Then we don't mess with other potential deploy step if we just change for the specific wiki repo.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 411 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Iex7CPZPPovE6Gx-:-Lh201ibBRRlwiGAeKUB:bd32pt7) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L411)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Add-Content "$HOME\.git-credentials" "https://$($GitUserName):$($GithubAccessToken)@github.com`n"
> ```

Instead of using this file, would it be possible to pass the token in the `git` calls, or just add the credentials to the wiki repo scope? My thought is to not have a file with the token on the build worker (even if it is for a time it is building).
If we need this file should remove it once we have deployed?
</blockquote></details>

I was following these [instructions](https://www.appveyor.com/docs/how-to/git-push/). I'll test to see if I can specify the credentials on the push url instead.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 423 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1JtLW1kuFEyJswf17:-Lh1siE5-ZE-V8udn6aS:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L423)) [...]

2019-06-10 22:57 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: 3 of 6 files reviewed, 17 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 408 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1HCvvCnan7H2qqRNP:-Lh2a7bx0GA2gko-R4DJ:bawr2d7) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L408)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had to move the `config core.autocrlf` back to global, as I was getting LF to CRLF warnings when executing the Git Clone.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 411 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Iex7CPZPPovE6Gx-:-Lh2aUhl6y2GSFGwNnW2:b-t50axb) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L411)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

I was following these [instructions](https://www.appveyor.com/docs/how-to/git-push/). I'll test to see if I can specify the credentials on the push url instead.
</blockquote></details>

I successfully tested using the remote set-url with the credentials on the URL. This looks cleaner to me, and the credentials are then purged along with the repo when we run `remove-item`


<!-- Sent from Reviewable.io -->

2019-06-10 23:01 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: 3 of 6 files reviewed, 17 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1E5ts15x0bmQ04zdz:-Lh2btKx27NJuvkLFnJp:b-285oqq) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The text in the PR description would be great to add as a new section under https://github.com/PowerShell/DscResource.Tests/blob/dev/README.md#deploy
</blockquote></details>

I'll do this when you guys have confirmed you are happy with the implementation.

---


<!-- Sent from Reviewable.io -->

2019-06-11 16:57 UTC, johlju reviewed
I will continue the review later or tomorrow,

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-Lh6TIsv8O9ivwUzKaI-:b-g1bwvk)* status: 3 of 6 files reviewed, 10 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 361 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1Fle6DwlgqeIo1fCF:-Lh6RBKT5PB6m0zQd4TU:b-70khrq) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L361)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Done.

These are just place holders. What user details do you want on the commits?
</blockquote></details>

Leave it as-is for now. We have to set up an account for this.


<!-- Sent from Reviewable.io -->

2019-06-11 18:13 UTC, johlju reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 408 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1HCvvCnan7H2qqRNP:-Lh6fwUB4egvbgaebwda:b-cieme3) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L408)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

I had to move the `config core.autocrlf` back to global, as I was getting LF to CRLF warnings when executing the Git Clone.
</blockquote></details>

Strange. :thinking: In the build worker git it is set to 'input' by default, I think. But why does the global override the local? :thinking: 
Anyway, we override this in the repos using a .gitattributes file, so I guess we can leave this as-is.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 428 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1K99b3OlQ8wqiOF3H:-Lh6gfhJ64fLJMOFDy7p:bj0gsfa) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Throw
> ```

`throw` (lower-case 't'). Throughout the code.
</blockquote></details>

There are two more `Throw` on line 410 and 421. :slightly_smiling_face: 
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 437 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1KTkPC4Is5eYHCRom:-Lh6eZel7iDD77z_tKQs:b-j5pnfj) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L437)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

You really want a scriptblock for a simple property comparison? It would also need to be:
```powershell
Where-Object -FilterScript { $_.fileName -like "$ResourceModuleName_*_wikicontent.zip" }
```
which I think is ugly.

How about this instead?

```powershell
Where-Object -Property filename -like "$ResourceModuleName_*_wikicontent.zip"
```
</blockquote></details>

I'm okay with your suggestion.


<!-- Sent from Reviewable.io -->

2019-06-11 20:09 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 428 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1K99b3OlQ8wqiOF3H:-Lh79495BB99iRuCGRIy:b-d204mb) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/DscResource.DocumentationHelper/WikiPages.psm1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There are two more `Throw` on line 410 and 421. :slightly_smiling_face: 
</blockquote></details>

Got them this time!


<!-- Sent from Reviewable.io -->

2019-06-12 15:37 UTC, johlju reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2019-06-12 15:39 UTC, johlju commented
@PlagueHO can you sign off on this implementation (and maybe review) so that @X-Guardian can update the README.md. That is my only comment left, and after that this PR looks good to me.

2019-06-12 18:40 UTC, X-Guardian commented
Did you see my comments on #227 and #228?

2019-06-23 09:49 UTC, X-Guardian commented
Hi @PlagueHO . Have you had chance to look at this PR yet? It would be great to get this implemented.

2019-06-24 08:57 UTC, PlagueHO requested changes
Sorry for the delay - I'm trying to get through all the reviews but day job is all consuming at the moment. I've not got through the whole review yet, but have put some thoughts in.

> Reviewed 1 of 3 files at r2, 1 of 4 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-Li7ghle7UiFSOLYVW50:b-go6ai3)* status: all files reviewed, 13 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[AppVeyor.psm1, line 1244 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1ENkrCwqQpCQABhr6:-Li7WfvG8j6qFfnWek9P:b-sedweu) ([raw file](https://github.com/powershell/dscresource.tests/blob/419a9c3b2a6ecb91806037c1b64619ab1e2b7e5e/AppVeyor.psm1#L1244)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

The `github_access_token` needs to be added to the `appveyor.yml` for each DSC Module repo before the publishing is going to work, as well as the Wiki site being initialised with a home page, so I would have this as opt-in so a managed roll-out can be done.
</blockquote></details>

I like opt-out model, but that would result in all repos getting broken when we merged this - as most repos won't have the `github_access_token` and the Wiki initialized (although we could possibly iniitialize the Wiki using GitHub API - haven't checked though).

So, initially I think we shouldn't use the opt-out model - especially as we'll probably want to test this one repo first. We can always come back and revisit this before enabling everyone to use it. We'll need to put some governance over `github_access_tokens` before we should encourage people to use it.

I also think we need to start looking at moving all these tasks over into a task execution framework like PSake (see https://github.com/PowerShell/DscResources/issues/243)
___
*[AppVeyor.psm1, line 1277 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7adewECTqwM8Np8GJ:-Li7adewECTqwM8Np8GK:b5u86qn) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/AppVeyor.psm1#L1277)):*
> ```PowerShell
> 
>         $startGalleryDeployParameters = @{
>             ResourceModuleName = $ResourceModuleName
> ```

Nitpick: As the other parameters in the block you added have aligned, can you align these ones? VS Code has an auto-format function that will do this for you (I always have it enabled and just press CTRL+ALT+F - I think I wrote a blog post on it some time back).
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 313 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7faH81NSGCsw4J7U1:-Li7faH81NSGCsw4J7U2:b-3k4m0k) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L313)):*
> ```PowerShell
>         The name of the Github Repo, in the format <account>/<repo>.
> 
>     .PARAMETER JobId
> ```

I'm thinking: Do we want to pull the Wiki content from the AppVeyor artifact or just use the content that was produced? It isn't a major issue, but being dependent on the JobId and AppVeyor itself limits our options to how we might use this in future.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 367 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7cLTp3jBE3tixszsF:-Li7cLTqDcZFXdhBbR4e:b-crgk6y) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L367)):*
> ```PowerShell
>         [Parameter()]
>         [System.String]
>         $GitUserEmail = 'appveyor@microsoft.com',
> ```

I'd worry about defaulting this to 'appveyor@microsoft.com' - this address may or may not be real, but we may run into problems if the automation is "acting" as publishing on behalf of a user at Microsoft (even not a real one).

One alternative could be that we default the Git details of the user of the commit that triggered the deploy (e.g. in most cases it'll be Katie).
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 372 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dQgbCTV-lGpxjSVu:-Li7dQgbCTV-lGpxjSVv:bsoc2sl) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L372)):*
> ```PowerShell
>         [System.String]
>         $GitUserName = 'AppVeyor'
>         )
> ```

Need to outdent this.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 376 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dTsOCmW3y-lUKBaX:-Li7dTsPEzcgAAPVwt4k:bh8iufq) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L376)):*
> ```PowerShell
>     $ErrorActionPreference = 'Stop'
> 
>     $script:apiUrl = 'https://ci.appveyor.com/api'
> ```

Could this be made a module level variable defined outside the function rather than a script scoped variable? Although I'm OK with script scope - it might be better moving it to the top of the module.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 383 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dnbFBnbGN0JfEFit:-Li7dnbG5IhcvbeZswRM:bvovqh7) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L383)):*
> ```PowerShell
> 
>     Write-Verbose -Message $script:localizedData.CreateTempDirMessage
>     $tempPath = [System.IO.Path]::GetTempPath()
> ```

Could I suggest moving this block into a new function -e.g. `New-TempFolder`  or something like that? Help meet Single Responsibility Principle (SRP).
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 384 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7diOjCCSvh8VI6WLj:-Li7diOjCCSvh8VI6WLk:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L384)):*
> ```PowerShell
>     Write-Verbose -Message $script:localizedData.CreateTempDirMessage
>     $tempPath = [System.IO.Path]::GetTempPath()
>     do
> ```

Can you add a blank line before this one?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 400 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7eZ_v6XJUnHh8ym_b:-Li7eZ_v6XJUnHh8ym_c:b-qh0w1a) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L400)):*
> ```PowerShell
>     $jobArtifactsUrl = "$apiUrl/buildjobs/$JobId/artifacts"
>     Write-Verbose -Message ($localizedData.DownloadAppVeyorArtifactDetailsMessage -f $JobId, $jobArtifactsUrl)
>     try
> ```

Can you add a blank line above this?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 412 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7f1xa5w7h4Am-2EGb:-Li7f1xb3x9BIFbM-jz9:bm1x3fw) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L412)):*
> ```PowerShell
>                 throw ($script:localizedData.NoAppVeyorJobFoundError -f $JobId)
>             }
>             Default
> ```

Can you add a blank line before this? Also 'default' needs to be lower case.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 420 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7f3oaDr_phg9mu6WM:-Li7f3oaDr_phg9mu6WN:bdpwvx2) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L420)):*
> ```PowerShell
> 
>     $wikiContentArtifact = $artifacts | Where-Object -Proper [...]

2019-06-24 11:00 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 13 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 313 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7faH81NSGCsw4J7U1:-Li87O7JESQmObkV_fYk:bdj2cq7) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L313)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm thinking: Do we want to pull the Wiki content from the AppVeyor artifact or just use the content that was produced? It isn't a major issue, but being dependent on the JobId and AppVeyor itself limits our options to how we might use this in future.
</blockquote></details>

I rather the step to build the auto-doc was moved to a deploy step too, and not run after tests has finished, then we could combine the auto doc step with this step. We could keep the after tests step too for debugging purposes and that step uploads the artifact, but the artifact isn’t used in the deploy step, at least not the artifact uploaded to AppVeyor. It could use the same source maybe.


<!-- Sent from Reviewable.io -->

2019-06-24 13:25 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 13 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[AppVeyor.psm1, line 1277 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7adewECTqwM8Np8GJ:-Li8Rei-74QWV_znS1fJ:bkf8er7) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/AppVeyor.psm1#L1277)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: As the other parameters in the block you added have aligned, can you align these ones? VS Code has an auto-format function that will do this for you (I always have it enabled and just press CTRL+ALT+F - I think I wrote a blog post on it some time back).
</blockquote></details>

OK, but I don't normally format code I haven't changed, as it confuses the commit and review.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 313 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7faH81NSGCsw4J7U1:-Li8bLz7AQU8AE4cm1hK:b-o13k7q) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L313)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I rather the step to build the auto-doc was moved to a deploy step too, and not run after tests has finished, then we could combine the auto doc step with this step. We could keep the after tests step too for debugging purposes and that step uploads the artifact, but the artifact isn’t used in the deploy step, at least not the artifact uploaded to AppVeyor. It could use the same source maybe.
</blockquote></details>

The auto-doc build step should be before the deploy. This gives you chance to examine the artifacts, load the Wiki pages into a test Wiki etc. before deployment (merge). The AppVeyor Wiki artifact IS used by the new `Publish-WikiContent` function, and it should be that way in the pipeline.
If we want to add a manual way of uploading Wiki pages, that can easily be added later, using PowerShell Parameter sets in the `Publish-WikiContent` function.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 367 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7cLTp3jBE3tixszsF:-Li8ZCd9E4Dw90DWf5J6:bh7nw97) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L367)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'd worry about defaulting this to 'appveyor@microsoft.com' - this address may or may not be real, but we may run into problems if the automation is "acting" as publishing on behalf of a user at Microsoft (even not a real one).

One alternative could be that we default the Git details of the user of the commit that triggered the deploy (e.g. in most cases it'll be Katie).
</blockquote></details>

Ok, I've changed the default for the `GitUserEmail` to `$env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL` and `GitUserName` to `$env:APPVEYOR_REPO_COMMIT_AUTHOR`
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 372 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dQgbCTV-lGpxjSVu:-Li8SUvR82dBgkbAc501:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L372)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Need to outdent this.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 376 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dTsOCmW3y-lUKBaX:-Li8SeVo0s6AUvbIc4a1:b-4gfp7c) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L376)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could this be made a module level variable defined outside the function rather than a script scoped variable? Although I'm OK with script scope - it might be better moving it to the top of the module.
</blockquote></details>

Done and renamed to `appVeyorApiUrl`
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 383 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7dnbFBnbGN0JfEFit:-Li8VVum-NKlYkSdT1um:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L383)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could I suggest moving this block into a new function -e.g. `New-TempFolder`  or something like that? Help meet Single Responsibility Principle (SRP).
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 384 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7diOjCCSvh8VI6WLj:-Li8UmEVBzPiKbs6VLwo:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L384)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 400 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7eZ_v6XJUnHh8ym_b:-Li8UwwX7IboclsDruIU:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L400)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line above this?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 412 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7f1xa5w7h4Am-2EGb:-Li8V5BQ-Yt8zKgq0oAX:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L412)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this? Also 'default' needs to be lower case.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 420 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7f3oaDr_phg9mu6WM:-Li8VAjoDybzdkikDfLF:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L420)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this? Also { needs to be on the next line
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 423 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7f4iTEaKs7TJ60P-Q:-Li8VHS30wqkSUTQrHzo:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L423)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 483 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7gaB_ED3X7WVaqBH4:-Li8VLax4OyPIXwXhxL1:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ [...]

2019-06-29 11:50 UTC, johlju reviewed
I pinged @PlagueHO about the pending PR's, so he will try to get on these his day job takes a lot of the day (the free time to) at the moment. 

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-LiY3CmUDFQNN9xcOO7l:b-4zi2r5)* status: all files reviewed, 13 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[AppVeyor.psm1, line 1277 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7adewECTqwM8Np8GJ:-LiY1pMcCO0r18sApZvr:bcdq0bw) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/AppVeyor.psm1#L1277)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

OK, but I don't normally format code I haven't changed, as it confuses the commit and review.
</blockquote></details>

That's fine, and I agree. It's @PlagueHO and my OCD that kicks in when we see something that for example doesn't follow the guideline or is consequent in the code. Just tell us when we go overboard and it should be another PR. :slightly_smiling_face: 
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 313 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7faH81NSGCsw4J7U1:-LiY2X839tvUVN4v5TiS:b-qiti5n) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L313)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

The auto-doc build step should be before the deploy. This gives you chance to examine the artifacts, load the Wiki pages into a test Wiki etc. before deployment (merge). The AppVeyor Wiki artifact IS used by the new `Publish-WikiContent` function, and it should be that way in the pipeline.
If we want to add a manual way of uploading Wiki pages, that can easily be added later, using PowerShell Parameter sets in the `Publish-WikiContent` function.
</blockquote></details>

Ah, I see your point. Agreed. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2019-06-29 21:54 UTC, PlagueHO requested changes
Thanks for being patient @X-Guardian - due to end of financial year work challenges I'm working 80 hour weeks to try and get through my work load so DSC is suffering (plus I maintain several other projects outside of DSC, run an Azure user group etc - I'm probably over committed :grin:). Only two more weeks of it and I should be able to keep more on top of it.

I realize myself and @Johlju can often be very OCD about things, but there is a correlation between code quality and code consistency and care (see Clean Code). Besides, after doing this for 5 or 6 years, we can't "unsee" style/consistency issues :grin:

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-Li_C6zY8zR90VGDuvke:bghjmuy)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 313 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li7faH81NSGCsw4J7U1:-Li_2zGPBD8gLk6Om3X_:bku3p4b) ([raw file](https://github.com/powershell/dscresource.tests/blob/cc07ed157d907eefcaa89acd90d8b0dc4d1e4fb9/DscResource.DocumentationHelper/WikiPages.psm1#L313)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Ah, I see your point. Agreed. :slightly_smiling_face: 
</blockquote></details>

I agree that the build step for the wiki content should occur during the build step. The dependency on AppVeyor artefacts is a bit of a bother - as perhaps splitting this function into two functions would with an orchestration function would actually allow us to more easily replace the Get-DscWikiContentArtifactFromAppVeyor:
Publish-DscResourceWikiSite ->
    Get-DscResourceWikiContentFromAppVeyor
    Publish-DscResourceWikiContentToGitHub

This would also better obey Single Responsibility Principle (SRP), and reduce the size of this function and make it easier to test.

But I'm OK with doing this later, so I've marked as satisfied.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 29 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_3rtIAU7VxHer_6Iw:-Li_3rtIAU7VxHer_6Ix:b2126rm) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L29)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         New-DscResourceWikiSite generates wiki pages that can be uploaded to GitHub to use as
> ```

The name of this function is not actually correct, and I think we should correct it. It should be something like Set-DscResourceWikiContentFromAppveyorArtifact - because we're not creating a new one and we're actually getting the content from an AppVeyor artifact and then updating the wiki with it. This name (although long) makes it much clearer the actual work that is being performed.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 385 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_An2A94gWsP5XMBGL:-Li_An2A94gWsP5XMBGM:b8vxz57) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L385)):*
> ```PowerShell
>     $path = New-TempFolder
> 
>     Write-Verbose -Message $script:localizedData.ConfigGlobalGitMessage
> ```

I'm wondering if it the code would flow better if all the git commands were together - occurring after the artifact is retrieved? I know the artifact code is dependent on the Git path, so copying the artifact content would still to occur in the git code. This would make future refactoring simpler (which could reduce the size of this function). 
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 494 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_6rYX2ZEwCcOinYtt:-Li_6rYX2ZEwCcOinYtu:b-oapfin) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L494)):*
> ```PowerShell
>         }
>     }
> }
> ```

I just realized - shouldn't we be cleaning up the temp folder here? We should wrap all the code in a try...finally to ensure it does happen.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 498 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_6NP26AownhPUvVdZ:-Li_6NP26AownhPUvVd_:b-t7f423) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L498)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Creates a new temporary folder with a random name
> ```

FYI, nitpick. Should end with full stops (and lines below).
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 519 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_6V-k40p8eZa8T_Pi:-Li_6V-k40p8eZa8T_Pj:b-8i3z1u) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L519)):*
> ```PowerShell
>     {
>         $name = [System.IO.Path]::GetRandomFileName()
>         $path = New-Item -Path $tempPath -Name $name -ItemType "directory" -ErrorAction SilentlyContinue
> ```

Should be single quotes (or quotes can be removed entirely) around Directory
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 521 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_75rb45DzAIjSOysM:-Li_75rb45DzAIjSOysN:b1kbfhh) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L521)):*
> ```PowerShell
>         $path = New-Item -Path $tempPath -Name $name -ItemType "directory" -ErrorAction SilentlyContinue
>     }
>     while (-not $path)
> ```

I just realized something here - if for some reason you were prevented from writing to the temp folder (it would be rare I know) then we'd hit a deadlock.

Might be worth implementing an internal counter with a throw if we tried too many times.

A real edge case, I know.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 922 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_884n8W8zGBIgHQj6:-Li_884n8W8zGBIgHQj7:b-cik2yv) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L922)):*
> ```PowerShell
> 
>     Describe 'DscResource.DocumentationHelper\WikiPages.psm1\Publish-WikiContent' {
> ```

Blank line should be removed.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1008 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_Bf710-GIkpRmwY4F:-Li_Bf710-GIkpRmwY4G:b912as) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1008)):*
> ```PowerShell
>             }
> 
>             It 'Should call the expected mocks' {
> ```

We don't seem to be validating the other calls to Git in the happy path test here - could we check this? I think it is worth ensuring all Git calls to occur at least (it'll be tricky to validate the order).

We could implement sad path tests for all the other Git calls, but it probably would add very little.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1058 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_A2Jv0Q_PIlzU1frt:-Li_A2Jv0Q_PIlzU1fru:bcx2sf0) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1058)):*
> ```PowerShell
>                         -Exactly -Times 1
>                 }
>                 Context 'When the AppVeyor job has no artifacts' {
> ```

Could you add a blank line before this line.


<!-- Sent from Reviewable.io -->

2019-06-29 23:19 UTC, PlagueHO reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 8 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 29 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_3rtIAU7VxHer_6Iw:-Li_WzLP4u8KFxdSX_ll:b-vp16mk) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L29)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The name of this function is not actually correct, and I think we should correct it. It should be something like Set-DscResourceWikiContentFromAppveyorArtifact - because we're not creating a new one and we're actually getting the content from an AppVeyor artifact and then updating the wiki with it. This name (although long) makes it much clearer the actual work that is being performed.
</blockquote></details>

Ignore this please! My bad - the header of this function was showing up above the new code you'd written.


<!-- Sent from Reviewable.io -->

2019-06-30 16:54 UTC, X-Guardian reviewed
No problem, we are all just doing this in our spare time. 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-Libh3MyDgFsm5yw8dva:b-qzjtbm)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 385 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_An2A94gWsP5XMBGL:-LibihYQ7vRAbfbROQ4H:b-qj8hmk) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L385)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm wondering if it the code would flow better if all the git commands were together - occurring after the artifact is retrieved? I know the artifact code is dependent on the Git path, so copying the artifact content would still to occur in the git code. This would make future refactoring simpler (which could reduce the size of this function). 
</blockquote></details>

I tried moving the `Invoke-Git config --global core.autocrlf true` to after the clone with the other commands, but then I was getting LF to CRLF warnings when executing the Git clone, so moved it back to before the clone.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 494 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_6rYX2ZEwCcOinYtt:-Lid6XnBBF63pz9vohN6:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L494)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I just realized - shouldn't we be cleaning up the temp folder here? We should wrap all the code in a try...finally to ensure it does happen.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 519 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_6V-k40p8eZa8T_Pi:-LibjQwU3VofVxXH-B9S:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L519)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be single quotes (or quotes can be removed entirely) around Directory
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 521 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_75rb45DzAIjSOysM:-LicrXBY0Q4lVbHQBfXx:bv1xjsi) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L521)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I just realized something here - if for some reason you were prevented from writing to the temp folder (it would be rare I know) then we'd hit a deadlock.

Might be worth implementing an internal counter with a throw if we tried too many times.

A real edge case, I know.
</blockquote></details>

Done, and added some tests for this function.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 922 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_884n8W8zGBIgHQj6:-LicsB9e7NSmBfzZahsM:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L922)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Blank line should be removed.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1008 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_Bf710-GIkpRmwY4F:-Lid3nN886weql4fytq5:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1008)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We don't seem to be validating the other calls to Git in the happy path test here - could we check this? I think it is worth ensuring all Git calls to occur at least (it'll be tricky to validate the order).

We could implement sad path tests for all the other Git calls, but it probably would add very little.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1058 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_A2Jv0Q_PIlzU1frt:-LicxLUM6A67ZrXsMOUT:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1058)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line before this line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-30 17:40 UTC, PlagueHO requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju and @X-Guardian)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1E5ts15x0bmQ04zdz:-LidSu3g7SJY7Ybpc0R5:ba5tq65) (no related file):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

I'll do this when you guys have confirmed you are happy with the implementation.
</blockquote></details>

Great job @X-Guardian - just a couple of minor style tweaks and we should be good to go. Did you want to add the section to the README.MD as @Johlju mentioned?

---
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 385 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Li_An2A94gWsP5XMBGL:-LidRzGR8zWND22NDw39:bbpy5ij) ([raw file](https://github.com/powershell/dscresource.tests/blob/3dad6d2ff9a885a5f40b1c6c81ed320a2e530dfa/DscResource.DocumentationHelper/WikiPages.psm1#L385)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

I tried moving the `Invoke-Git config --global core.autocrlf true` to after the clone with the other commands, but then I was getting LF to CRLF warnings when executing the Git clone, so moved it back to before the clone.
</blockquote></details>

Ok, no worries - thought it was worth a try.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 385 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidS44pDVRCQgZ0Yw32:-LidS44pDVRCQgZ0Yw33:br2twoy) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L385)):*
> ```PowerShell
>     $path = New-TempFolder
> 
>     try {
> ```

Can you put { on the next line?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 455 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidS94T1E6Bg50tdmtd:-LidS94T1E6Bg50tdmte:b-gz0jiz) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L455)):*
> ```PowerShell
>         Pop-Location
>     }
>     finally {
> ```

Can you move the { to the next line?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 484 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidSPCx1yu_-zt_uHv6:-LidSPCx1yu_-zt_uHv7:b-z4t95j) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L484)):*
> ```PowerShell
>     )
> 
>     Write-Debug "Invoking Git $Arguments"
> ```

Sorry, missed this - can you use -Message parameter


<!-- Sent from Reviewable.io -->

2019-06-30 19:36 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1E5ts15x0bmQ04zdz:-Lidrstk-dpLx9a3o8uM:bp61qj1) (no related file):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Great job @X-Guardian - just a couple of minor style tweaks and we should be good to go. Did you want to add the section to the README.MD as @Johlju mentioned?
</blockquote></details>

Cheers @PlagueHO, will do.

---
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 385 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidS44pDVRCQgZ0Yw32:-LidrzTV0B14dQ3NM75D:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L385)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you put { on the next line?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 455 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidS94T1E6Bg50tdmtd:-Lids15x7O1louQsBGq6:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L455)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you move the { to the next line?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 484 at r8](https://reviewable.io/reviews/powershell/dscresource.tests/324#-LidSPCx1yu_-zt_uHv6:-LidsTS42mNWlsJR8RrR:b-wskwrv) ([raw file](https://github.com/powershell/dscresource.tests/blob/ccfda0e9179491352b6a755c6074f2b3a6cd88dc/DscResource.DocumentationHelper/WikiPages.psm1#L484)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Sorry, missed this - can you use -Message parameter
</blockquote></details>

Done and localized.


<!-- Sent from Reviewable.io -->

2019-07-01 09:54 UTC, PlagueHO approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/324#-Lh1E5ts15x0bmQ04zdz:-LigxDuKEEX5SRBUOphc:b-bcatcj) (no related file):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Cheers @PlagueHO, will do.
</blockquote></details>

Awesome @X-Guardian - everything looks good. Once the README.MD is in I'll merge. Thanks again!

---


<!-- Sent from Reviewable.io -->

2019-07-02 16:54 UTC, johlju reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r8, 2 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/324#-:-LinaxQt3Rek1CMP6HNL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-02 20:04 UTC, PlagueHO commented
Hi @X-Guardian , @johlju - sorry for not completing this last night, I was flying home. I'm trying to sign off on the bus but reviewable isnt working on my phone.

:lgtm:

2019-07-03 06:57 UTC, merged