New-DscResourcePowerShellHelp: Update Function and Add Tests
PowerShell/DscResource.Tests pull request #325
Opened 2019-06-13 00:24 UTC by X-Guardian

#### Pull Request (PR) description

This PR updates the `New-DscResourcePowerShellHelp` function with the following features

- Output help files to resource specific path
- Fix example content processing
- String localization
- Pester tests

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-06-28 10:36 UTC, johlju commented
I will help review this one, but will be off travelling for a few days, so will help get on this them unless someone haven't already reviewed it.

2019-06-29 11:27 UTC, johlju reviewed
This is awesome work @X-Guardian!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325#-:-LiXytYrATJjKa8nS146:b-3kzgj0)* status: all files reviewed, 5 unresolved discussions (waiting on @X-Guardian)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXz35x0UWT2OHlahQh:-LiXz35x0UWT2OHlahQi:b6bemj2) (no related file):*
Would you mind adding a short text about this functionality under this section? It would be easier discovered by others until we can automate this process.
https://github.com/PowerShell/DscResource.Tests#documentation-helper-module

Non-blocking since it is not done before, and we can do that in another PR.

---
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwuCDAu0tT9uTNpGH:-LiXwuCDAu0tT9uTNpGI:bp175hg) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
> ```
> $script:output
> ```

Why do we need to use `$script:` for the variable inside the function? Normally $script should be used for variable in the script scope (outside of the functions) :thinking: 
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 86 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXw_Rn5zvCSiHfkPFT:-LiXw_Rn5zvCSiHfkPFU:bj7s6ng) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L86)):*
> ```
> "`n    "
> ```

Why do we add whitespace after the new line here? Below `[Environment]::NewLine` is used, should we use that to be consequent? 
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 87 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwfEi91t-zmwvrqeC:-LiXwfEi91t-zmwvrqeD:ba6he3e) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L87)):*
> ```
> "    # Description",
> ```

Why hardcode white spaces before? Can we regex this instead maybe?  :thinking: 
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 131 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXxRzr2xEoF-_gx8BV:-LiXxRzr2xEoF-_gx8BW:beb7d9l) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L131)):*
> ```
> else {
> ```

Open brace should be on a separate row.


<!-- Sent from Reviewable.io -->

2019-06-29 17:18 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: all files reviewed, 5 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwuCDAu0tT9uTNpGH:-LiZ2ku5APLEjS8qQYvE:b-hubt45) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $script:output
> ```

Why do we need to use `$script:` for the variable inside the function? Normally $script should be used for variable in the script scope (outside of the functions) :thinking: 
</blockquote></details>

This is so the variable can be referenced in the Pester tests. Please let me know if you know another of doing this that works.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 86 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXw_Rn5zvCSiHfkPFT:-LiZ3aad8kC5L9u8fp0Y:bidm7vy) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L86)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "`n    "
> ```

Why do we add whitespace after the new line here? Below `[Environment]::NewLine` is used, should we use that to be consequent? 
</blockquote></details>

This is to indent every line. This is the original code, not something I have changed.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 87 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwfEi91t-zmwvrqeC:-LiZ3xrVDN8EXF_nNyaH:b-5d2rq5) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L87)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "    # Description",
> ```

Why hardcode white spaces before? Can we regex this instead maybe?  :thinking: 
</blockquote></details>

These spaces weren't needed. I've removed them and adjusted the test. I've also made it 'swallow' the next blank line for consistency.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 131 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXxRzr2xEoF-_gx8BV:-LiZ32F6AFUk9Rgzr1Ah:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L131)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> else {
> ```

Open brace should be on a separate row.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-29 23:15 UTC, PlagueHO requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: all files reviewed, 17 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwuCDAu0tT9uTNpGH:-Li_P8AyD3vrajqecppL:baxq14y) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

This is so the variable can be referenced in the Pester tests. Please let me know if you know another of doing this that works.
</blockquote></details>

Ideally we want to limit the need for unit tests to have to "see into" the coding being tested as this results in brittle test. The exception is of course Mocks.

So why don't we just validate the input on the Out-File is what we expect - after all, that it fundamentally the purpose of this functioN?
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 72 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NdvI2jTsO8iY2Cik:-Li_NdvI2jTsO8iY2Cil:b-y13jxp) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L72)):*
> ```PowerShell
>         $mofFileObject = $_
> 
>         $result = (Get-MofSchemaObject -FileName $_.FullName) | Where-Object {
> ```

Can you add -FilterScript parameter here?
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 73 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Nu-T63m34QJd0zin:-Li_Nu-T63m34QJd0zio:b-err87u) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L73)):*
> ```PowerShell
> 
>         $result = (Get-MofSchemaObject -FileName $_.FullName) | Where-Object {
>             ($_.ClassName -eq $mofFileObject.Name.Replace(".schema.mof", "")) `
> ```

Existing code, but can you change to single quotes?
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 76 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Nnwa5D9QL42YCc8B:-Li_NnwbDCRBc8dnWh8I:b-64mlxy) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L76)):*
> ```PowerShell
>                 -and ($null -ne $_.FriendlyName)
>         }
>         $descriptionPath = Join-Path -Path $mofFileObject.DirectoryName -ChildPath "readme.md"
> ```

Should be single quotes around readme.md
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 77 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NlbO33pW0-6W-6wx:-Li_NlbO33pW0-6W-6wy:b-24h7qd) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L77)):*
> ```PowerShell
>         }
>         $descriptionPath = Join-Path -Path $mofFileObject.DirectoryName -ChildPath "readme.md"
>         if (Test-Path -Path $descriptionPath)
> ```

Add blank line before
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Ostc9lUCAZkjVHBp:-Li_Ostc9lUCAZkjVHBq:bm4okxu) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
> ```PowerShell
>             Write-Verbose -Message ($script:localizedData.GenerateHelpDocumentMessage -f $result.FriendlyName)
> 
>             $script:output = ".NAME" + [Environment]::NewLine
> ```

My big problem with this function is that it is using string concatenation which at this length is a code smell we should get rid of. I know it is all existing code, but it might be better to refactor it now as you've added other SB code further down.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 95 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_TUms-ImYk8AWY1id:-Li_TUmu8iSwderIteJ5:b-v2tn0f) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L95)):*
> ```PowerShell
>             {
>                 $script:output += ".PARAMETER $($property.Name)" + [Environment]::NewLine
>                 $script:output += "    $($property.State) - $($property.DataType)"
> ```

Doing indents like this is prone to error.

Suggest assigning a variable called $indent (or whatever) and assign it as;
```powershell
[System.String]::new(' ',4)
```

Then using it throughout.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 98 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_RPs33K2pQV94RIZe:-Li_RPs33K2pQV94RIZf:b-v0k58i) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L98)):*
> ```PowerShell
>                 $script:output += [Environment]::NewLine
> 
>                 if ([string]::IsNullOrEmpty($property.ValueMap) -ne $true)
> ```

Why not `if (-not [string]::IsNullOrEmpty($property.ValueMap))`?
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 101 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_SdSc1Kan6l1I0Ujw:-Li_SdSe69ycKe-3ez3O:byptq9y) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L101)):*
> ```PowerShell
>                 {
>                     $script:output += "    Allowed values: "
>                     $property.ValueMap | ForEach-Object {
> ```

Needs `-Process`
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 104 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_QoyxEZLr8B7e2UI9:-Li_QoyxEZLr8B7e2UIA:b-u1a93n) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L104)):*
> ```PowerShell
>                         $script:output += $_ + ", "
>                     }
>                     $script:output = $script:output.TrimEnd(" ")
> ```

Why don't we ust use a `-join` to replace this entire code block?
```powershell
$script:output += "    Allowed values: {0}" -f ($property.ValueMap -join ', ')
```
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 121 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NPe4CxP9YPmTUnqL:-Li_NPe5-LPLXt2Ca1z-:bw03j45) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L121)):*
> ```PowerShell
> 
>                 Write-Verbose -Message "Found $($exampleFiles.count) Examples for resource $($result.FriendlyName)"
>                 foreach ($exampleFile in $exampleFiles)
> ```

Add blank line before this one.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 168 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_U_Hb1hCmwEIPmo2u:-Li_U_HcCcAv7oeO3Ny7:b-a2adgr) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L168)):*
> ```PowerShell
>         and converts it to help text in preparation for being added to a PowerShell help file.
> #>
> ```

Remove blank line (my fault as I left this in the code too).
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1298 at r2](https://reviewable.io/reviews/power [...]

2019-06-30 09:23 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: 2 of 3 files reviewed, 17 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwuCDAu0tT9uTNpGH:-Libey672suxKEq4ODa7:bl8zvan) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Ideally we want to limit the need for unit tests to have to "see into" the coding being tested as this results in brittle test. The exception is of course Mocks.

So why don't we just validate the input on the Out-File is what we expect - after all, that it fundamentally the purpose of this functioN?
</blockquote></details>

I've changed all these `$script:output` references back to `$output`pending a solution with the pester test itself.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 72 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NdvI2jTsO8iY2Cik:-LibUODS-F1vqnhdI4l4:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L72)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add -FilterScript parameter here?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 73 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Nu-T63m34QJd0zin:-LibUOxb65ogkpit0ZTk:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L73)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Existing code, but can you change to single quotes?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 76 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Nnwa5D9QL42YCc8B:-LibUV1a1crwCbkLuyY2:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L76)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be single quotes around readme.md
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 77 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NlbO33pW0-6W-6wx:-LibUcVP7FqzXcNZ0Q_C:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L77)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Add blank line before
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Ostc9lUCAZkjVHBp:-Libf9ad6Kxl5mbHyIsP:b-frleb9) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

My big problem with this function is that it is using string concatenation which at this length is a code smell we should get rid of. I know it is all existing code, but it might be better to refactor it now as you've added other SB code further down.
</blockquote></details>

Sorry Daniel, but my view is this is existing code and this and the other change requests below are outside the scope of what this PR was supposed to do. You are basically asking me to re-write the function! How about we get this PR done and then raise another issue/PR to look at these other changes.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 95 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_TUms-ImYk8AWY1id:-Libfk156nqO_pzooWfn:bo9ebf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L95)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doing indents like this is prone to error.

Suggest assigning a variable called $indent (or whatever) and assign it as;
```powershell
[System.String]::new(' ',4)
```

Then using it throughout.
</blockquote></details>

Existing code. Comment as above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 98 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_RPs33K2pQV94RIZe:-Libfm-I--dpoWAQ4GY4:bo9ebf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L98)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why not `if (-not [string]::IsNullOrEmpty($property.ValueMap))`?
</blockquote></details>

Existing code. Comment as above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 101 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_SdSc1Kan6l1I0Ujw:-LibgIPsEtXYPnlKp824:bo9ebf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L101)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs `-Process`
</blockquote></details>

Existing code. Comment as above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 104 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_QoyxEZLr8B7e2UI9:-LibfvdL6S5KQO4PhrQ_:bo9ebf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L104)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why don't we ust use a `-join` to replace this entire code block?
```powershell
$script:output += "    Allowed values: {0}" -f ($property.ValueMap -join ', ')
```
</blockquote></details>

Existing code. Comment as above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 121 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NPe4CxP9YPmTUnqL:-LibVKP501MqIkzhC_xQ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L121)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Add blank line before this one.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 168 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_U_Hb1hCmwEIPmo2u:-LibXC2348U8KGPcr-QP:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L168)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Remove blank line (my fault as I left this in the code too).
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1298 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Vqc6420MUYgKbD98:-LibeYSd9-Zo75qrtPFq:b5ti6ks) ([raw file](https: [...]

2019-06-30 17:29 UTC, PlagueHO requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: all files reviewed, 6 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Ostc9lUCAZkjVHBp:-LidONykBSvVUo86ctAA:bb77ogg) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Sorry Daniel, but my view is this is existing code and this and the other change requests below are outside the scope of what this PR was supposed to do. You are basically asking me to re-write the function! How about we get this PR done and then raise another issue/PR to look at these other changes.
</blockquote></details>

I agree that this should be refactored in a separate PR (I've created an issue to track it here: https://github.com/PowerShell/DscResource.Tests/issues/328). However, because you'd made changes to the code/function we generally apply "boy scout rule" - which means we'll raise any recommendations against any code touched by the PR - even if it is beyond the specific intent of the PR. That is what all reviewers are expected to do and how we keep the code base clean and optimal. We need to continuously address technical debt otherwise the results is resources like xActiveDirectory and xWebAdministration which are basically drowning in it and requires monumental effort and dedication (a huge thank you to you for doing that BTW :grin:) to clean up. Anyway, as you've undone the changes to this function we can do it in another PR.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 95 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_TUms-ImYk8AWY1id:-LidPlqL-xYtDJB-dC9n:bribihm) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L95)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Existing code. Comment as above.
</blockquote></details>

As above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 98 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_RPs33K2pQV94RIZe:-LidPnwuA3JflcjXVNC4:bribihm) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L98)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Existing code. Comment as above.
</blockquote></details>

As above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 101 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_SdSc1Kan6l1I0Ujw:-LidPqYjCRLv-zgDCu2y:bribihm) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L101)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Existing code. Comment as above.
</blockquote></details>

As above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 104 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_QoyxEZLr8B7e2UI9:-LidPtVWB5E5mWI5yAeB:bribihm) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L104)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Existing code. Comment as above.
</blockquote></details>

As above.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 121 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_NPe4CxP9YPmTUnqL:-LidPvgo42aYYcFOVaj4:bribihm) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/DscResource.DocumentationHelper/PowerShellHelp.psm1#L121)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As above.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1298 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Vqc6420MUYgKbD98:-LidQAPt4x_r_fqaUHf_:b-hgirjr) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1298)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Sorry Daniel, I can't see any way of capturing the input to a mocked function. Can you give me a pointer?
</blockquote></details>

If you're Mocking the Out-File command, then use (I'm just typing this freehand so might be not quite correct):
```powershell
Assert-MockCalled -CommandName Out-File -ParameterFilter { $InputObject -eq $script:mockPowerShellHelpOutput -and $FilePath -eq ...whatever it was }
```

Sorry about brevity here, but I'm writing this on Airport Wifi at 5:30AM, which is up-and-down like a yoyo and keeps disconnecting me.


<!-- Sent from Reviewable.io -->

2019-07-01 14:23 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @johlju, @PlagueHO, and @X-Guardian)

___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 81 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwuCDAu0tT9uTNpGH:-LihubwW93jz05sAonIm:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L81)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

I've changed all these `$script:output` references back to `$output`pending a solution with the pester test itself.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/PowerShellHelp.psm1, line 87 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXwfEi91t-zmwvrqeC:-LihuWya3ujV-CtSkrsX:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2a1dc5bff2c93eca3d96f86e88b66834e62cee23/DscResource.DocumentationHelper/PowerShellHelp.psm1#L87)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

These spaces weren't needed. I've removed them and adjusted the test. I've also made it 'swallow' the next blank line for consistency.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1298 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Vqc6420MUYgKbD98:-LihuLm8CjMCFtrocjeU:b-jzr5nv) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1298)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If you're Mocking the Out-File command, then use (I'm just typing this freehand so might be not quite correct):
```powershell
Assert-MockCalled -CommandName Out-File -ParameterFilter { $InputObject -eq $script:mockPowerShellHelpOutput -and $FilePath -eq ...whatever it was }
```

Sorry about brevity here, but I'm writing this on Airport Wifi at 5:30AM, which is up-and-down like a yoyo and keeps disconnecting me.
</blockquote></details>

Cheers Daniel, that was great. Done.


<!-- Sent from Reviewable.io -->

2019-07-03 06:58 UTC, PlagueHO commented
Hi @X-Guardian - can you resolve the conflicts on this one and we'll get it complete and merged. Cheers!

2019-07-03 07:01 UTC, PlagueHO requested changes
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: all files reviewed, 6 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[README.md, line 578 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiqcWaB4V7t2wfzV_Ro:-LiqcWaB4V7t2wfzV_Rp:b-pr29k8) ([raw file](https://github.com/powershell/dscresource.tests/blob/a106aebd155dd0a0e87923945a995d146d818bef/README.md#L578)):*
> ```Markdown
> description and examples where they exist.
> 
> a README.md with a text description must exist in the resource's subdirectory for the
> ```

Sentence needs to start with a capital A
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1298 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/325#-Li_Vqc6420MUYgKbD98:-LiqckD2ENHmwodpuMck:b-8o237f) ([raw file](https://github.com/powershell/dscresource.tests/blob/a299f63f7accd5c6f305da92c9287536e48ad3db/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1298)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Cheers Daniel, that was great. Done.
</blockquote></details>

Great stuff!


<!-- Sent from Reviewable.io -->

2019-07-03 07:20 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @johlju and @PlagueHO)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiXz35x0UWT2OHlahQh:-Liqh4hh7E4a9xRRaM8p:bb6un1j) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would you mind adding a short text about this functionality under this section? It would be easier discovered by others until we can automate this process.
https://github.com/PowerShell/DscResource.Tests#documentation-helper-module

Non-blocking since it is not done before, and we can do that in another PR.
</blockquote></details>

Done

---
___
*[README.md, line 578 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/325#-LiqcWaB4V7t2wfzV_Ro:-LiqgwMMBEP7FmCd-D5C:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a106aebd155dd0a0e87923945a995d146d818bef/README.md#L578)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Sentence needs to start with a capital A
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-03 07:30 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/325#-:-LiqjYILA0i7oMy8tv1a:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2019-07-03 07:30 UTC, merged