Publish-WikiContent: Add Wiki Sidebar, Footer and WikiSource File Copy
PowerShell/DscResource.Tests pull request #335
Opened 2019-07-10 21:54 UTC by X-Guardian

#### Pull Request (PR) description

This PR adds an auto-generated Sidebar and Footer to the `Publish-WikiContent` function, as well as copying any files within a `WikiSource` directory of the repo into the Wiki.

#### This Pull Request (PR) fixes the following issues

- Fixes #227
- Fixes #228

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-07-11 11:34 UTC, johlju commented
@X-Guardian Do you have an example on how this will look like in any of you public repos/forks?

2019-07-11 11:47 UTC, X-Guardian commented
Yes. my fork of xActiveDirectory has its [Wiki](https://github.com/X-Guardian/xActiveDirectory/wiki) created from this function:

2019-07-11 12:00 UTC, johlju reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335)* status: all files reviewed, 14 unresolved discussions (waiting on @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 333 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVs0n-466MfxiLK2dW:-LjVs0n-466MfxiLK2dX:bjdsika) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L333)):*
> ```
> .EXAMPLE
> ```

This example need to be updated to reflect the new parameter since it is needed when run locally?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 358 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVrvRBAuvL12xOYMc8:-LjVrvRBAuvL12xOYMc9:b-gt328p) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L358)):*
> ```
> $MainModulePath
> ```

This parameter should be added to comment-based help.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 568 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqQ0QB8tUSHtXMN-c:-LjVqQ0QB8tUSHtXMN-d:bpyvzu8) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L568)):*
> ```
> {
> ```

Open brace should be on its own row.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 572 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVpzg04taIaRv90Oov:-LjVpzg04taIaRv90Oow:bhxhtjc) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L572)):*
> ```
> parameter
> ```

`Parameter` (upper-case 'P'). Throughout the new code.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 575 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVq5C69jqu5KZvhkxY:-LjVq5C69jqu5KZvhkxZ:b-mn94aa) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L575)):*
> ```
> [parameter(Mandatory = $true)]
> ```

We should have a blank row before this one.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 590 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqYPe5jIBfD-xdX5Q:-LjVqYPe5jIBfD-xdX5R:b-o8ptvy) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L590)):*
> ```
> Foreach
> ```

`foreach` (lower-case 'f')
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 609 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqV3-EWQtQ52hNB7b:-LjVqV3-EWQtQ52hNB7c:bpyvzu8) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L609)):*
> ```
> {
> ```

Open brace should be on its own row.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 616 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqH32CAKvLSPJGf_I:-LjVqH32CAKvLSPJGf_J:b-b8lo3y) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L616)):*
> ```PowerShell
>         [System.String]
>         $ResourceModuleName,
>         [parameter(Mandatory = $true)]
> ```

We should have a blank row before this one.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 648 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqVk23fWA50l5LKdD:-LjVqVk23fWA50l5LKdE:bpyvzu8) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L648)):*
> ```
> {
> ```

Open brace should be on its own row.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 655 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqI3R8uV0MrdPDCbW:-LjVqI3R8uV0MrdPDCbX:b-b8lo3y) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L655)):*
> ```PowerShell
>         [System.String]
>         $MainModulePath,
>         [parameter(Mandatory = $true)]
> ```

We should have a blank row before this one.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 660 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVsn2z2uA_w68Jx4wV:-LjVsn2z2uA_w68Jx4wW:ba0iwca) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L660)):*
> ```
> 'WikiSource'
> ```

Is this just a temp folder? Not seeing it used anywhere else. Is it from that folder the files should be published, then how did they get there? Or are this just additional files to get published?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 664 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqb6s67QcR631guVh:-LjVqb6s67QcR631guVi:b-o8ptvy) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L664)):*
> ```
> Foreach
> ```

`foreach` (lower-case 'f')
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1291 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVt_ZL8zGunV_viztE:-LjVt_ZL8zGunV_viztF:b-68eipu) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1291)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>         $mockSetWikiSideBarParms = @{
>             ResourceModuleName = 'TestResource'
>             Path               = $env:temp
>         }
> 
>         $mockFileInfo = @(
>             @{
>                 Name     = 'resource1.md'
>                 BaseName = 'resource1'
>                 FullName = "$($env:temp)\resource1.md"
>             }
>         )
> 
>         $wikiSideBarFileBaseName = '_Sidebar.md'
>         $wikiSideBarFileFullName = Join-Path -Path $mockSetWikiSideBarParms.Path -ChildPath $wikiSideBarFileBaseName
> 
>         Mock Out-File
> ```
</details>


Can we add all of this inside a `BeforeAll`-block? Throughout.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1310 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVth9z-HDspdMX-lZv:-LjVth9z-HDspdMX-lZw:bbng8r6) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1310)):*
> ```
> Mock Get-ChildItem -MockWith { $mockFileInfo }
> ```

Can we add this inside a `BeforeAll`-block? Throughout.


<!-- Sent from Reviewable.io -->

2019-07-11 20:12 UTC, X-Guardian reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335)* status: 3 of 5 files reviewed, 14 unresolved discussions (waiting on @johlju)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 333 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVs0n-466MfxiLK2dW:-LjXXSZ1Bslk28qWCLq_:bn60mvv) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L333)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> .EXAMPLE
> ```

This example need to be updated to reflect the new parameter since it is needed when run locally?
</blockquote></details>

Done, and improved the function description.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 358 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVrvRBAuvL12xOYMc8:-LjXY6JX5hOp6LBKRwKT:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L358)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $MainModulePath
> ```

This parameter should be added to comment-based help.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 568 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqQ0QB8tUSHtXMN-c:-LjXYB527HTXDwBXcK7p:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L568)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> {
> ```

Open brace should be on its own row.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 572 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVpzg04taIaRv90Oov:-LjXYS6eCbMxoFibaxA8:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L572)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> parameter
> ```

`Parameter` (upper-case 'P'). Throughout the new code.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 575 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVq5C69jqu5KZvhkxY:-LjXYa8U7TKHdnV8w631:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L575)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [parameter(Mandatory = $true)]
> ```

We should have a blank row before this one.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 590 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqYPe5jIBfD-xdX5Q:-LjXYeK26Q8ML-QEpn9S:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L590)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Foreach
> ```

`foreach` (lower-case 'f')
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 609 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqV3-EWQtQ52hNB7b:-LjXYjWg3GtQwaED3ftn:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L609)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> {
> ```

Open brace should be on its own row.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 616 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqH32CAKvLSPJGf_I:-LjXYlHjBhPJ4ONvfVtY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L616)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have a blank row before this one.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 648 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqVk23fWA50l5LKdD:-LjXYoKNDk0I6LyuU9sy:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L648)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> {
> ```

Open brace should be on its own row.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 655 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqI3R8uV0MrdPDCbW:-LjXYpRl-9yiz5uqEIfj:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L655)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have a blank row before this one.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 660 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVsn2z2uA_w68Jx4wV:-LjXYwfk17CjG7HKjJoy:buom5d5) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L660)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'WikiSource'
> ```

Is this just a temp folder? Not seeing it used anywhere else. Is it from that folder the files should be published, then how did they get there? Or are this just additional files to get published?
</blockquote></details>

Any files in this folder within the repo will get copied into the Wiki. I can parameterise it with a default if  you like.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 664 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVqb6s67QcR631guVh:-LjXYvphEphg5M11vKZT:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L664)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Foreach
> ```

`foreach` (lower-case 'f')
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1291 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVt_ZL8zGunV_viztE:-LjXdJ6SDugocXMytELh:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1291)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         $mockSetWikiSideBarParms = @{
>             ResourceModuleName = 'TestResource'
>             Path               = $env:temp
>         }
> 
>         $mockFileInfo = @(
>             @{
>                 Name     = 'resource1.md'
>                 BaseName = 'resource1'
>                 FullName = "$($env:temp)\resource1.md"
>             }
>         )
> 
>         $wikiSideBarFileBaseName = '_Sidebar.md'
>         $wikiSideBarFileFullName = Join-Path -Path $mockSetWikiSideBarParms.Path -ChildPath $wikiSideBarFileBaseName
> 
>         Mock Out-File
> ```

Can we add all of this inside a `BeforeAll`-block? Throughout. [...]

2019-07-12 09:30 UTC, PlagueHO requested changes
We might need to notify the repo maintainers for the other Auto documentation repos (aside from myself) that this change will require them to copy additional wiki files into the WikiSource folder of the main repo - otherwise they will get lost from the sidebar etc.

For example, SharepointDsc uses a custom Sidebar: https://github.com/PowerShell/SharePointDsc/wiki

We'll need to loop @ykuijs and @NikCharlebois into this as I think they'll need to be aware of this one. I can take care of all the other repos that will be affected.

What we should do is allow the WikiSource folder to contain main, sidebar etc files that override the generated ones.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-Lj_RLUJ2IzYEDecDjAC:b-h9pr22)* status: all files reviewed, 23 unresolved discussions (waiting on @johlju and @X-Guardian)

___
*[README.md, line 818 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UCPo0V47r_vGdVBP:-Lj_UCPo0V47r_vGdVBQ:b-qp2si8) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/README.md#L818)):*
> ```Markdown
> A Wiki Sidebar file will be generated, containing links to all of the markdown
> files in the Wiki, as well as as a Wiki Footer file. Any files contained within the
> `WikiSource` directory of the repository will also be published to the Wiki.
> ```

Could we ensure it is clear that these files will override any generated ones?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 363 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_QSXQAVObp9HJrnXC:-Lj_QSXQAVObp9HJrnXD:bl38jlx) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L363)):*
> ```PowerShell
>         [Parameter()]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

Can you use [System.String] for consistency?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 561 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_QlLd1YmmNv982UZs:-Lj_QlLd1YmmNv982UZt:brkwgby) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L561)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Creates the Wiki side bar file from the list of markdown files in the path
> ```

Can you end with full stop (and the other help entries too).
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 598 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_R43H7etfba7oEShr:-Lj_R43H7etfba7oEShs:b-26ji8y) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L598)):*
> ```PowerShell
> 
>     $wikiFiles = Get-ChildItem -Path $Path -Filter '*.md'
>     foreach ($file in $wikiFiles)
> ```

Actually needs a blank line before and after this entire block.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 645 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UPgV9JoRKmUAzfZt:-Lj_UPgV9JoRKmUAzfZu:b4zhs05) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L645)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Copies any Wiki files from the module into the Wiki.
> ```

Mention that this should overwrite any exiting files.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 676 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_Spq2372V5drXOIhp:-Lj_Spq390RjNSwxmtZ6:bk3ygn9) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L676)):*
> ```PowerShell
> 
>     $wikiFiles = Get-ChildItem -Path $wikiSourcePath
>     foreach ($file in $wikiFiles)
> ```

Needs blank lines around this block.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 679 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UTX3-fKz0FCIDnuu:-Lj_UTX3-fKz0FCIDnuv:bfqccc) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L679)):*
> ```PowerShell
>     {
>         Write-Verbose -Message ($localizedData.CopyFileMessage -f $file.name)
>         Copy-Item -Path $file.fullname -Destination $Path
> ```

Will need a `-Force` to overwrite any existing files.
___
*[DscResource.DocumentationHelper/en-US/WikiPages.strings.psd1, line 22 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_Vo59AY2PEQGEkZJR:-Lj_Vo59AY2PEQGEkZJS:b-wg2ei) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/en-US/WikiPages.strings.psd1#L22)):*
> ```PowerShell
>     GenerateWikiFooterMessage                  = Generating Wiki Footer '{0}'.
>     CopyWikiFilesMessage                       = Copying Wiki files from '{0}'.
>     CopyFileMessage                            = Copying file '{0}'.
> ```

Minor nitpick: Could the message mention that this is being copied to the wiki?
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1307 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_VVTA-089Yrsos4JE:-Lj_VVTA-089Yrsos4JF:b1gr1dj) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1307)):*
> ```PowerShell
>             $wikiSideBarFileFullName = Join-Path -Path $mockSetWikiSideBarParms.Path -ChildPath $wikiSideBarFileBaseName
> 
>             Mock Out-File
> ```

Minor nitpick - can you use `Mock -CommandName` - and throughout.


<!-- Sent from Reviewable.io -->

2019-07-12 19:02 UTC, johlju reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335)* status: all files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 660 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVsn2z2uA_w68Jx4wV:-LjbY6_5BcAT_n7qnWPc:b-v8evci) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L660)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Any files in this folder within the repo will get copied into the Wiki. I can parameterise it with a default if  you like.
</blockquote></details>

Yeah, I think we should have a parameter, but instead of a default I think the caller should callit with `'WikiSource'`so it's clear in the main function (Publish-WikiContent) that it's using that folder.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1312 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjbYpk2A3kXUDQFQEAG:-LjbYpk2A3kXUDQFQEAH:b-xsk9v6) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1312)):*
> ```
> Mock Get-ChildItem
> ```

Should use named parameters `-CommandName` throughout.


<!-- Sent from Reviewable.io -->

2019-07-12 19:04 UTC, johlju reviewed
Yes, I was having that in mind to, I thought we need to loop in other maintainers too. Also looked at SharePointDsc and saw that they used a sidebar that doesnt look hw this suggest it should look at. We should also add all the WikiSource documents to the Sidebar (if it is not already done).

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-LjbZDplBP8_Pd2VI7qR:b-oh6b4n)* status: all files reviewed, 11 unresolved discussions (waiting on @X-Guardian)



<!-- Sent from Reviewable.io -->

2019-07-12 19:36 UTC, X-Guardian reviewed
Don't forget guys that this function isn't being used in any repos yet and it is opt in too. It also won't lose any pre-existing Wiki files that aren't in the WikiSource folder.
I would recommend that if Repos are going to opt-in to this function, then they go with the auto-generated sidebar, otherwise what is the point?

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-Ljbf-0-0oPURiJz64ZU:bhkdhjs)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[README.md, line 818 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UCPo0V47r_vGdVBP:-LjbbEVq6dfAtiaPWQkK:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/README.md#L818)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could we ensure it is clear that these files will override any generated ones?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 660 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjVsn2z2uA_w68Jx4wV:-Ljbd76ZCJaunGi7tGTk:b-hfzax7) ([raw file](https://github.com/powershell/dscresource.tests/blob/e781faa8d22df7d9b944f43ec8507668b0c66d28/DscResource.DocumentationHelper/WikiPages.psm1#L660)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yeah, I think we should have a parameter, but instead of a default I think the caller should callit with `'WikiSource'`so it's clear in the main function (Publish-WikiContent) that it's using that folder.
</blockquote></details>

Done. I've made it a mandatory parameter in the `Copy-WikiFile` function and a non-mandatory parameter of `Publish-WikiContent` with a default of 'WikiSource'.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 363 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_QSXQAVObp9HJrnXC:-LjbbIxT6Ce3T5gIDNXx:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L363)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use [System.String] for consistency?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 561 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_QlLd1YmmNv982UZs:-LjbbRFe0zL_8xEy_LMh:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L561)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you end with full stop (and the other help entries too).
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 598 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_R43H7etfba7oEShr:-LjbbYss3HkycKpWWhxQ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L598)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Actually needs a blank line before and after this entire block.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 645 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UPgV9JoRKmUAzfZt:-LjbbiyoEA6QUrtErpqZ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L645)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Mention that this should overwrite any exiting files.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 676 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_Spq2372V5drXOIhp:-LjbdX8v2P1Xav2mr3mB:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L676)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs blank lines around this block.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 679 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-Lj_UTX3-fKz0FCIDnuu:-Ljbdo-9-5bckCQo2lXr:b-ghg5h8) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/DscResource.DocumentationHelper/WikiPages.psm1#L679)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Will need a `-Force` to overwrite any existing files.
</blockquote></details>

Done. I've added it, but `Copy-Item` only needs `-Force` to overwrite read-only files.
___
*[Tests/Unit/DscResource.DocumentationHelper.Tests.ps1, line 1312 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/335#-LjbYpk2A3kXUDQFQEAG:-Ljbev_62lwzFC4XT3fI:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2ad05e783850ee07a1b521d93c6be849bb00d3c/Tests/Unit/DscResource.DocumentationHelper.Tests.ps1#L1312)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Mock Get-ChildItem
> ```

Should use named parameters `-CommandName` throughout.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-13 17:15 UTC, johlju reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Don't forget guys that this function isn't being used in any repos yet and it is opt in too. 

Right, this function was just added recently, I forgot. My thought was that this could have been used manually and then the behaviour would change with this PR. Since that is not the case I don't see a problem with just merging this.

> Reviewed 2 of 4 files at r6, 2 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-LjgJWo099U_tY7wkNGt:bxnc4dc)* status: all files reviewed, 7 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-07-13 17:16 UTC, johlju commented
@PlagueHO must resolve his comment too, but at least this looks good to me. 🙂

2019-07-13 21:27 UTC, PlagueHO approved these changes
@X-Guardian - doh - didn't click to this. Good point.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-LjhDZK30twJv1OE46cS:bnpoy4g)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-13 21:27 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/335#-:-LjhDzCRA5Q7oszVPJMd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-13 21:27 UTC, merged