PSScriptAnalyzer: One Space Between Keyword and Parenthesis check
PowerShell/DscResource.Tests pull request #347
Opened 2019-09-12 07:24 UTC by SSvilen

#### Pull Request (PR) description
One Space Between Keyword and Parenthesis
If a keyword is followed by a parenthesis, there should be single space between the keyword and the parenthesis.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-09-12 08:26 UTC, PlagueHO commented
Thanks @SSvilen - I'll quickly run the DSCResource.Analyzer process using your branch and see how many repos fail. Give me an hour (it takes about that long to run :cry: )

2019-09-12 08:58 UTC, PlagueHO commented
Hi @SSvilen - it looks like I'm finding some false positives being thrown:
![image](https://user-images.githubusercontent.com/7589164/64769922-4b84f880-d5a0-11e9-9576-105bd33f9cc1.png)

I suspect this is for methods in functions:
```powershell
if (-not [System.String]::IsNullOrEmpty($resultObject.ErrorString))
```

2019-09-12 19:25 UTC, SSvilen reviewed
Yeah.. I adjusted the check and hopefully should be ok now. I've tested against the ActiveDirectoryCSDsc resource. 
![image.png](https://files.reviewableusercontent.io/images/reviewable/10175251/g90q3MQSwuvpc2YRvJ84iKRT/image.png)
 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-LoavLBK0mZ9JgDtxuji:bojrxhq)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-13 06:39 UTC, PlagueHO commented
Thanks @SSvilen - I'll re-run the tests now.

2019-09-13 20:25 UTC, PlagueHO commented
Here are the logs of the tests (ignore the test drive issue):
```
! Dan@PLAGUE02 : ~\Source\GitHub\DscResource.Analysis : [master ≡]> Get-DscResourceKitInformation |
>>             Where-Object -FilterScript { $_.MetaTestOptIn -contains 'Common Tests - Custom Script Analyzer Rules' } |
>>             Start-DscResourceKitMetaTest `
>>                 -TestFrameworkUri 'https://github.com/SSvilen/DscResource.Tests' `
>>                 -TestFrameworkBranch 'KeywordSpaceAfterCheck' `
>>                 -TestName 'Common Tests - PS Script Analyzer on Resource Files'
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1565 (delta 6), reused 13 (delta 4), pack-reused 1543
Receiving objects: 100% (1565/1565), 322.11 KiB | 544.00 KiB/s, done.
Resolving deltas: 100% (940/940), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc\DSCResource.Tests'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1986 (delta 11), reused 21 (delta 7), pack-reused 1956
Receiving objects: 100% (1986/1986), 851.24 KiB | 731.00 KiB/s, done.
Resolving deltas: 100% (1205/1205), done.
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
Tests completed in 184.45s
Tests Passed: 42, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 4331 (delta 31), reused 29 (delta 10), pack-reused 4252
Receiving objects: 100% (4331/4331), 1.73 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (2786/2786), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1986 (delta 11), reused 21 (delta 7), pack-reused 1956
Receiving objects: 100% (1986/1986), 851.24 KiB | 951.00 KiB/s, done.
Resolving deltas: 100% (1205/1205), done.
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
New-PSDrive : A drive with the name 'TestDrive' already exists.
At C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\TestDrive.ps1:18 char:17
+ ...     $null = & $SafeCommands['New-PSDrive'] -Name $DriveName -PSProvid ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (TestDrive:String) [New-PSDrive], SessionStateException
    + FullyQualifiedErrorId : DriveAlreadyExists,Microsoft.PowerShell.Commands.NewPSDriveCommand

      [-] Error occurred in Context block 0ms
        Win32Exception: Access is denied
        UnauthorizedAccessException: Access is denied
        at Remove-TestDriveSymbolicLinks, C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\TestDrive.ps1: line 120
        at Remove-TestDrive, C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\TestDrive.ps1: line 142
        at DescribeImpl, C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\Describe.ps1: line 207
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Keyword' errors need to be fixed:
WARNING: MSFT_ADUser.psm1 (Line 3): If a keyword is followed by a parenthesis, there should be single space between the keyword and the parenthesis. See
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 22.1s
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
    [-] Error occurred in Describe block 0ms
      ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
      at Remove-TestDrive, C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\TestDrive.ps1: line 144
      at DescribeImpl, C:\Users\Dan\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Functions\Describe.ps1: line 207
Tests completed in 537.6s
Tests Passed: 131, Failed: 3, Skipped: 0, Pending: 0, Inconclusive: 0
Cloning into 'C:\Users\Dan\AppData\Local\Temp\CertificateDsc'...
remote: Enumerating objects: 3413, done.
remote: Total 3413 (delta 0), reused 0 (delta 0), pack-reused 3413
Receiving objects: 100% (3413/3413), 763.52 KiB | 704.00 KiB/s, done.
Resolving deltas: 100% (2204/2204), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\CertificateDsc\DSCResource.Tests'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1986 (delta 11), reused 21 (delta 7), pack-reused 1956
Receiving objects: 100% (1986/1986), 851.24 KiB | 778.00 KiB/s, done.
Resolving deltas: 100% (1205/1205), done.
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\CertificateDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
Tests completed in 127.06s
Tests Passed: 30, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ComputerManagementDsc'...
remote: Enumerating objects: 4404, done.
remote: Total 4404 (delta 0), reused 0 (delta 0), pack-reused 4404
Receiving objects: 100% (4404/4404), 970.67 KiB | 814.00 KiB/s, done.
Resolving deltas: 100% (2733/2733), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ComputerManagementDsc\DSCResource.Tests'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1986 (delta 11), reused 21 (delta 7), pack-reused 1956
Receiving objects: 100% (1986/1986), 851.24 KiB | 876.00 KiB/s, done.
Resolving deltas: 100% (1205/1205), done.
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\ComputerManagementDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Keyword' errors need to be fixed:
WARNING: MSFT_Computer.psm1 (Line 642): If a keyword is followed by a parenthesis, there should be single space between the keyword and the parenthesis. See
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 21.57s
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ComputerManagementDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Keyword' err [...]

2019-09-13 20:31 UTC, PlagueHO commented
The resources that pass/fail:
- [x] ActiveDirectoryCSDsc
- [ ] ActiveDirectoryDsc - 1 issue - @johlju 
- [ ] ComputerManagementDsc - 3 issues - @PlagueHO 
- [x] FileContentDsc
- [x] FSRMDsc
- [x] iSCSIDsc
- [x] NetworkingDsc
- [ ] SecurityPolicyDsc - 1 issue - ???
- [ ] SqlServerDsc - 6 issues - @johlju 
- [x] StorageDsc
- [x] WmiNamespaceSecurityDsc
- [x] WSManDsc
- [x] xBitlocker
- [ ] xExchange - 10+ issues - ???
- [ ] xPSDesiredStateConfiguration - 10+ issues - @PlagueHO 
- [ ] xWebAdministration - 10+ issues - @johlju

2019-09-13 20:33 UTC, PlagueHO commented
I'd suggest with this one that we don't merge it till after the release this week - we don't want to block any resources from being released at the last minute. I'll begin submitting PR's to ComputerManagementDsc and xPSDesiredStateConfiguration today.

2019-09-13 21:06 UTC, johlju commented
We squash a lot of style issues with these rules! so great! 😁 I will fix the repos above. 

Agree we don’t merge this until after the release.

2019-09-14 12:14 UTC, SSvilen reviewed
Cool. So no false positives? 
Let me know if your think another rule would be helpful. 
I really enjoy writing psscriptanalyzer rules. 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-Lojg1jXDzPuvQ7tIHFj:b-ri4mzo)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-14 12:20 UTC, johlju commented
We will see if there a false positives once we start to resolve the repos. :)

@SSvilen Another one that I see often that would be great to get as a rule https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects

2019-09-14 12:33 UTC, SSvilen reviewed
That would be fun. I'm on it.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-Lojkb-k8ylwVZhu3ksi:b-u4956i)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-15 15:03 UTC, johlju commented
@PlagueHO SqlServerDsc is done and merged.

2019-09-16 05:43 UTC, PlagueHO commented
Cool, thanks @johlju - I'll get my ones done tonight.

2019-09-16 09:10 UTC, PlagueHO commented
@SSvilen , @johlju - I've submitted PR's for both ComputerManagementDsc and xPSDesiredStateConfiguration - but due to boyscout rule I ended up having to do a LOT of clean up on xPSDesiredStateConfiguration. So might take a little bit to get reviewed.

2019-09-21 08:01 UTC, johlju commented
@PlagueHO PR merged for ActiveDirectoryDsc. Resolved SecurityPolicyDsc and xExchange, waiting for review and merge. Will do xWebAdministration later - need to go out and work a bit in the garden/forest.

2019-09-21 08:05 UTC, PlagueHO commented
@johlju  - I'm still getting xPSDesiredStateConfigration merged. But after that I reckon we just merge this PR.

2019-09-21 13:24 UTC, johlju commented
PR merged for xWebAdministration. I'm waiting for xExchange and SecurityPolicyDsc to be merged.

2019-09-21 14:56 UTC, johlju commented
Yes just merge this PR :) We got another custom rule we need to work on thanks to @SSvilen. 

Let’s make hactoberfest issues for those :)

2019-09-21 19:32 UTC, PlagueHO requested changes
Only a couple of style changes here @Svilen - Great stuff.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-LpKItzoDXB_FKTG0iMn:b-kw14jm)* status: all files reviewed, 2 unresolved discussions (waiting on @SSvilen)

___
*[CHANGELOG.md, line 80 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/347#-LpKIRPc9p1LFi0MF5Tf:-LpKIRPc9p1LFi0MF5Tg:bfmsh35) ([raw file](https://github.com/powershell/dscresource.tests/blob/a4dc55f0d2ef846b1d17b3ab9743bb1d4ec23730/CHANGELOG.md#L80)):*
> ```Markdown
> - Removed the legacy `CHANGELOG` link in the `README.md` table of contents.
> - Fixed broken links and formatting in the `README.md` file.
> - Added Measure-Keyword function to check if all keywords are in lower case and if followed by parentheses, that there is a single space in between.
> ```

Can you split this line so that it wraps at less than 80 characters?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1050 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/347#-LpKIrXl8171nRdKMLRe:-LpKIrXl8171nRdKMLRf:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/a4dc55f0d2ef846b1d17b3ab9743bb1d4ec23730/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1050)):*
> ```PowerShell
>             $script:diagnosticRecord -as $diagnosticRecordType
>         }
>         foreach ($item in $tokenWithNoSpace)
> ```

Can you add a blank line before this one?


<!-- Sent from Reviewable.io -->

2019-09-22 16:12 UTC, SSvilen reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 80 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/347#-LpKIRPc9p1LFi0MF5Tf:-LpOj0Sl10J2PfYEcvfm:b-kxowid) ([raw file](https://github.com/powershell/dscresource.tests/blob/a4dc55f0d2ef846b1d17b3ab9743bb1d4ec23730/CHANGELOG.md#L80)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you split this line so that it wraps at less than 80 characters?
</blockquote></details>

I made this update a sub-update. 
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1050 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/347#-LpKIrXl8171nRdKMLRe:-LpOjTLB6LhvcX12naPP:b-1y4v17) ([raw file](https://github.com/powershell/dscresource.tests/blob/a4dc55f0d2ef846b1d17b3ab9743bb1d4ec23730/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1050)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

That's going to be my next psscriptanalyzer check.. 


<!-- Sent from Reviewable.io -->

2019-09-22 18:00 UTC, SSvilen reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-LpP7SD30YHXOAqMETop:bnfp4nl)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-09-23 09:40 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/347#-:-LpSUXTS8dezc0gK7R23:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1050 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/347#-LpKIrXl8171nRdKMLRe:-LpSUTfG6coGic-aI5pO:be67ikx) ([raw file](https://github.com/powershell/dscresource.tests/blob/a4dc55f0d2ef846b1d17b3ab9743bb1d4ec23730/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1050)):*
<details><summary><i>Previously, SSvilen (Svilen) wrote…</i></summary><blockquote>

That's going to be my next psscriptanalyzer check.. 
</blockquote></details>

Nice! :grin:


<!-- Sent from Reviewable.io -->

2019-09-23 09:40 UTC, merged