Hashtables - correct formatting check
PowerShell/DscResource.Tests pull request #348
Opened 2019-09-16 20:01 UTC by SSvilen

#### Pull Request (PR) description

Hashtables and Objects should be written in the following format. Each property should be on its own line indented once.

$hashtable = @{
    Key1 = 'Value1'
    Key2 = 2
    Key3 = '3'
}

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-09-21 13:15 UTC, johlju commented
@SSvilen Awesome work on this one! Thank you! This one will probably generate a lot of issues that need to be resolved in the modules. 🙂 

PlagueHO Do you have time to review this one?

2019-09-21 13:15 UTC, johlju commented
@PlagueHO Do you have time to review this one?

2019-09-21 20:29 UTC, PlagueHO commented
@johlju - yep, will get onto this one today.

2019-09-21 22:40 UTC, PlagueHO requested changes
Great stuff @Svilen - just some minor style issues.

I'll also run your branch against all the repos to see what shows up.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpKyk_I7thycAlXFN8d:b-vuenno)* status: all files reviewed, 18 unresolved discussions (waiting on @SSvilen)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1056 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuYny5EaOiz16iwzf:-LpKuYnz3xog8irtQz9P:bfzkdwc) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1056)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>     Validates all hashtables.
> ```

Can you indent this line (and the other help section content lines)?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1077 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuhc48eDMfy-kDIZ8:-LpKuhc48eDMfy-kDIZ9:bup20d4) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1077)):*
> ```PowerShell
>     [CmdletBinding()]
>     [OutputType([Microsoft.Windows.Powershell.ScriptAnalyzer.Generic.DiagnosticRecord[]])]
>     param(
> ```

LOL - looks like you need to add a space after the param :grin:
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1082 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKup8-1rVrGPbgqV8P:-LpKup8-1rVrGPbgqV8Q:b-vcllgh) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1082)):*
> ```PowerShell
>         [System.Management.Automation.Language.HashtableAst[]]
>         $HashtableAst
>     )
> ```

Can you add a blank line after this one?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1091 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvNc0C2znd81t5pxy:-LpKvNc0C2znd81t5pxz:bbe0nxq) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1091)):*
> ```PowerShell
>             $hashtableLines = $hashtable.Extent.Text -split '\n'
> 
>             #hashtable should start with '@{' and end with '}'
> ```

Can you add a space after the # and start comment with a capital letter?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1103 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvL4KAimPYpT_RQB7:-LpKvL4KAimPYpT_RQB8:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1103)):*
> ```PowerShell
>                 $initialIndent = ([regex]::Match($hashtable.Extent.StartScriptPosition.Line, '(\s*)')).Length
>                 $expectedLineIndent = $initialIndent + 5
>                 foreach ($keyValuePair in $hashtable.KeyValuePairs)
> ```

Can you add a blank line before this one?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3377 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvS1ECtH0nP3zjtW1:-LpKvS1ECtH0nP3zjtW2:b2f7koz) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3377)):*
> ```PowerShell
> 
> Describe 'Measure-Hashtable' {
> ```

Can you remove this blank line?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3378 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvTff2pdMkH1OA_7X:-LpKvTff2pdMkH1OA_7Y:b-jzxe3y) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3378)):*
> ```PowerShell
> Describe 'Measure-Hashtable' {
> 
>     Context "When calling the function directly" {
> ```

Can you convert to single quotes?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3428 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyPq7EvS4YwHYMZj2:-LpKyPq7EvS4YwHYMZj3:bw0aqn) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3428)):*
> ```PowerShell
>         }
> 
>         Context "When hashtable is correctly formatted" {
> ```

Can you use single quotes?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3429 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyRn64-ugDyMwftM1:-LpKyRn64-ugDyMwftM2:bw0aqn) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3429)):*
> ```PowerShell
> 
>         Context "When hashtable is correctly formatted" {
>             It "Correctly formatted non-nested hashtable" {
> ```

Can you use single quotes?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3441 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyTgMBS_JzEOa6DdZ:-LpKyTgMBS_JzEOa6Dd_:b-10emr9) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3441)):*
> ```PowerShell
>                 $record = Measure-Hashtable -HashtableAst $mockAst
>                 ($record | Measure-Object).Count | Should -Be 0
>             }
> ```

Can you add a blank line after this one?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3442 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKySon7muMgGA_u8de:-LpKySon7muMgGA_u8df:bw0aqn) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3442)):*
> ```PowerShell
>                 ($record | Measure-Object).Count | Should -Be 0
>             }
>             It "Correctly formatted nested hashtable" {
> ```

Can you use single quotes?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3461 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyW-G3qbtRC_qPTiA:-LpKyW-G3qbtRC_qPTiB:bw0aqn) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3461)):*
> ```PowerShell
>     }
> 
>     Context "When calling PSScriptAnalyzer" {
> ```

Can you use single quotes?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3467 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKya9J7u0qR4SB5kun:-LpKya9J7u0qR4SB5kuo:b-10emr9) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3467)):*
> ```PowerShell
>             }
>             $ruleName = "$($script:ModuleName)\Measure-Hashtable"
>         }
> ```

Can you add a blank line after this one?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3468 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyYVpAwrKS5Vk6NuS:-LpKyYVq0XVAEj7Gh0nM:bofl1p) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3468)):*
> ```PowerShell
>             $ruleName = "$($script:ModuleName)\Measure-Hashtable"
>         }
>          Context 'When hashtable is not correctly formatted' {
> ```

Indent seems incorrect here.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3509 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKye0dBUI9pCEVyuKE:-LpKye0dBUI9pCEVyuKF:bw0aqn) ([raw file](https://github.com/p [...]

2019-09-21 22:46 UTC, PlagueHO reviewed
Just running against the repo and it looks like there is a false positive showing up. Empty hashtables are showing as violations. E.g. https://github.com/PowerShell/ActiveDirectoryCSDsc/blob/dev/DSCResources/MSFT_AdcsCertificationAuthority/MSFT_AdcsCertificationAuthority.psm1#L207

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpL-34m4jK-Jfx6zhDL:b-i3a93j)* status: all files reviewed, 18 unresolved discussions (waiting on @SSvilen)



<!-- Sent from Reviewable.io -->

2019-09-22 07:48 UTC, johlju commented
FYI. Sent in PR https://github.com/PowerShell/DscResources/pull/531 to update the style guideline so it is more clear that we write `@{}` for empty hashtables.

2019-09-22 20:18 UTC, SSvilen reviewed
OK I'll update the check's logic. 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpOkL7D-SBwaVP83dWG:b-n2bjlr)* status: 3 of 6 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1056 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuYny5EaOiz16iwzf:-LpOkZFXCehyPbHet1r-:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1056)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you indent this line (and the other help section content lines)?
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1077 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuhc48eDMfy-kDIZ8:-LpOkabSEJvK_1OP2D2l:b-5e3ynl) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1077)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

LOL - looks like you need to add a space after the param :grin:
</blockquote></details>

Thank god there is a check for that :) are the meta tests turned on for this repo? I branched out of dev, where this check is not yet merged. 
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1082 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKup8-1rVrGPbgqV8P:-LpOocKY9VmG7XUsAGoP:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1082)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1091 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvNc0C2znd81t5pxy:-LpP7Zvj6PLamwxAx2YE:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1091)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a space after the # and start comment with a capital letter?
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1103 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvL4KAimPYpT_RQB7:-LpP7dlZ59wzTLGzJRLo:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1103)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3377 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvS1ECtH0nP3zjtW1:-LpP7n6P4cuKZGF01uqc:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3377)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this blank line?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3378 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKvTff2pdMkH1OA_7X:-LpP7syq1j3qNsEbMFcd:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3378)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you convert to single quotes?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3428 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyPq7EvS4YwHYMZj2:-LpP81IR3cmStddfPqD4:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3428)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3429 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyRn64-ugDyMwftM1:-LpP81t1Be60Ijg-38LV:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3429)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3441 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyTgMBS_JzEOa6DdZ:-LpP87uBBwCBHA1Rmz9w:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3441)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3442 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKySon7muMgGA_u8de:-LpP8J9V9h9pS3bxUQqH:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3442)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3461 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyW-G3qbtRC_qPTiA:-LpP8Kwe6TCXNimqg-AF:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3461)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3467 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKya9J7u0qR4SB5kun:-LpP8P2K2AS2Xzr8YCcR:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3467)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3468 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKyYVpAwrKS5Vk6NuS:-LpP8X5K5nhBWwYFAOe0:b-old9p6) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3468)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Indent seems incorrect here.
</blockquote></details>

Looks fine to me.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3509 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKye0dBUI9pCEVyuKE:-LpP8iP10n2d1ukDGmCL:b-896fix) ([raw file](https://github. [...]

2019-09-23 19:26 UTC, SSvilen reviewed
That's just a rebase against the current dev branch.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpU_F0u0erKJGoAyNTP:br61e8f)* status: 1 of 6 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-09-26 07:30 UTC, PlagueHO requested changes
Changes looking great. I'll just run this against all the repos and see what shows up!

> Reviewed 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpgTVb9-9op-rspfILo:b-lrju9v)* status: all files reviewed, 1 unresolved discussion (waiting on @SSvilen)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1077 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuhc48eDMfy-kDIZ8:-LpgNdA557HqK7VeheBw:bvfmy4x) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1077)):*
<details><summary><i>Previously, SSvilen (Svilen) wrote…</i></summary><blockquote>

Thank god there is a check for that :) are the meta tests turned on for this repo? I branched out of dev, where this check is not yet merged. 
</blockquote></details>

That is a good point - they should be turned on, but I don't think they are. At least worth turning them on in the .VSCode settings.


<!-- Sent from Reviewable.io -->

2019-09-26 18:41 UTC, PlagueHO reviewed
Ok, it's going to take me a little while to look through some of the results here, because it looks like we've got quite a few violations on this one. I'll take a look tonight.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LpiroHYDPsJLdHy6vIy:bqp2aef)* status: all files reviewed, 1 unresolved discussion (waiting on @SSvilen)



<!-- Sent from Reviewable.io -->

2019-09-27 12:57 UTC, SSvilen reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1077 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuhc48eDMfy-kDIZ8:-Lpmmovq9T5F3gUI72cA:b75rkkp) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1077)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

That is a good point - they should be turned on, but I don't think they are. At least worth turning them on in the .VSCode settings.
</blockquote></details>

I'll do it tomorrow and publish it as part of this PR. 


<!-- Sent from Reviewable.io -->

2019-10-04 05:00 UTC, PlagueHO commented
Sorry about the delay, but here is the logs of what needs to be fixed (a lot):
```text
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.

Receiving objects: 100% (1570/1570), 323.42 KiB | 545.00 KiB/s, done.
Resolving deltas: 100% (945/945), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc\DSCResource.Tests'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 2071 (delta 1), reused 3 (delta 1), pack-reused 2057
Receiving objects: 100% (2071/2071), 920.01 KiB | 997.00 KiB/s, done.
Resolving deltas: 100% (1263/1263), done.
    ____            __
   / __ \___  _____/ /____  _____
  / /_/ / _ \/ ___/ __/ _ \/ ___/
 / ____/  __(__  ) /_/  __/ /
/_/    \___/____/\__/\___/_/
Pester v4.9.0
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_AdcsEnrollmentPolicyWebService.psm1 (Line 478): Hashtable is not correctly formatted. See
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 1.35s
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryCSDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
Tests completed in 13.53s
Tests Passed: 41, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc'...
remote: Enumerating objects: 4384, done.
                                                                                  s:  98% (4297/4384), 1.50 MiB | 1.46 MiB/s
Receiving objects: 100% (4384/4384), 1.71 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (2849/2849), done.
Cloning into 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 2071 (delta 1), reused 3 (delta 1), pack-reused 2057
Receiving objects: 100% (2071/2071), 920.01 KiB | 678.00 KiB/s, done.
Resolving deltas: 100% (1263/1263), done.
    ____            __
   / __ \___  _____/ /____  _____
  / /_/ / _ \/ ___/ __/ _ \/ ___/
 / ____/  __(__  ) /_/  __/ /
/_/    \___/____/\__/\___/_/
Pester v4.9.0
Executing all tests in 'C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1' matching test name Common Tests - PS Script Analyzer on Resource Files
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_ADComputer.psm1 (Line 831): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: MSFT_ADComputer.psm1 (Line 832): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 1.5s
        Expected $null, but got @(Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord).
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_ADDomainTrust.psm1 (Line 495): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 1.39s
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_ADForestProperties.psm1 (Line 182): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: MSFT_ADForestProperties.psm1 (Line 207): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 1.36s
        Expected $null, but got @(Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord).
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_ADReplicationSiteLink.psm1 (Line 174): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all custom DSC Resource Kit PSSA rules 1.66s
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
        577:                         $customPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\Users\Dan\AppData\Local\Temp\ActiveDirectoryDsc\DSCResource.Tests\Meta.Tests.ps1: line 577
WARNING: Custom DSC Resource Kit PSSA rule(s) did not pass.
WARNING: The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
WARNING: MSFT_ADServicePrincipalName.psm1 (Line 115): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: MSFT_ADServicePrincipalName.psm1 (Line 142): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
WARNING: For instructions on how to run PSScriptAnalyzer on your own machi [...]

2019-10-04 21:16 UTC, PlagueHO commented
List of resources with violations:
- [ ] ActiveDirectoryDsc - @johlju?
- [ ] FSRMDsc - PR raised by @PlagueHO.
- [ ] iSCSIDsc - PR raised by @PlagueHO.
- [ ] WSManDsc - @PlagueHO raising PR.
- [ ] xBitlocker - @mhendric?
- [ ] xExchange - @mhendric?
- [ ] xPSDesiredStateConfiguration - @PlagueHO raising PR.
- [ ] xWebAdministration - @johlju?

2019-10-05 09:49 UTC, SSvilen commented
I can do some also - like xexchange or any of the others you have , @plagueho?

2019-10-05 15:37 UTC, johlju commented
Just send in PR for any you like :)

2019-10-05 15:39 UTC, johlju commented
I have a bunch of reviews to do this weekend so I probably won’t have anytime until next weekend. @ssvilen you may resolve xWebAdministration if you like.

2019-10-05 19:17 UTC, SSvilen reviewed
I just have one question - is this better 
```powershell
    Write-FunctionEntry -Parameters @{'MailboxServer' = $MailboxServer; 'DAGName' = $DAGName } -Verbose:$VerbosePreference
```
or this
```powershell
Write-FunctionEntry -Parameters @{
        'MailboxServer' = $MailboxServer
        'DAGName'       = $DAGName
    } -Verbose:$VerbosePreference
```

Don't know - looks like an edge case to me. 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LqSLDZ0BchMk0GBQEeP:b-e7hqft)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-10-05 19:24 UTC, johlju commented
We should format the hash table as your later example to follow the style guideline.

2019-10-05 20:27 UTC, PlagueHO commented
Regarding the empty hash table format, there is an issue open in PSSA relating to this: https://github.com/PowerShell/PSScriptAnalyzer/issues/1346

2019-10-06 07:09 UTC, johlju commented
I will create an issue in xWebAdministration to resolve that repo and see if someone picks it up.

2019-10-06 07:10 UTC, johlju commented
Also for ActiveDriectoryDsc.

2019-10-06 07:21 UTC, johlju commented
I added these issue so that someone can pick them up (before I have time to resolve them)
https://github.com/PowerShell/xWebAdministration/issues/524
https://github.com/PowerShell/ActiveDirectoryDsc/issues/516
https://github.com/PowerShell/SqlServerDsc/issues/1437

2019-10-07 10:22 UTC, johlju commented
Please see this comment https://github.com/PowerShell/xWebAdministration/issues/524#issuecomment-538936954 feel there are an issue (edge case) with the rule here? 🤔

2019-10-07 13:36 UTC, SSvilen commented
In the rule I've assumed that the hashtable ends with \s*} (as regex).
In other words - the line contains only closing parenthesis leaded only by whitespace charachters.
So
```powershell
 '});' 
```
would violate it,
but
```powershell
  } 
```
won't

2019-10-07 14:23 UTC, johlju commented
Ah, so putting the parenthesis on the next row will solve this.

2019-10-09 19:41 UTC, SSvilen reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1077 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/348#-LpKuhc48eDMfy-kDIZ8:-Lqm1_km7JLItJGsujY5:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/93e1715ad58f9a59573426ad806759bd3ded7eba/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1077)):*
<details><summary><i>Previously, SSvilen (Svilen) wrote…</i></summary><blockquote>

I'll do it tomorrow and publish it as part of this PR. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-10 06:40 UTC, PlagueHO approved these changes
@Johlju - do you reckon we merge this one or wait for the update to PSSA/VSCode PS extension?

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LqoMyRrCIPOzvykC8VH:b-1jphcj)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-18 19:17 UTC, PlagueHO commented
@SSvilen - can you resolve the merge conflicts on this one? @johlju - I reckon we just merge this one after that - what say you?

2019-10-20 13:59 UTC, johlju commented
Yes, let’s merge this. I will fix any problem in any repo that I maintain. And in others if there is an issue with release or something

2019-10-20 22:00 UTC, SSvilen reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LrfAqH8CgD_C-U0lbqo:b-896fix)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-10-21 05:46 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-LrgqSra7SpPnW3IUqQ4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-21 05:48 UTC, PlagueHO commented
@SSvilen - LOL, I was about to merge this but noticed that the tests are failing because the Hash Tables are in the wrong format :grin:

https://ci.appveyor.com/project/PowerShell/dscresource-tests/builds/28245419?fullLog=true#L307

Can you fix these?

2019-10-26 20:33 UTC, PlagueHO commented
@SSvilen - are you still working on this one?

2019-10-26 21:24 UTC, SSvilen reviewed
Sorry @plagueHo - that must have slipped through... I thought that there are still DSC Repos, that have to be fixed.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-Ls8wisO5JsmCTCrHjQc:b-q04p1v)* status: 6 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-26 22:03 UTC, PlagueHO approved these changes
No worries at all @SSVilen! I think they're all either done now or we're just going to deal with them once this is through.

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-Ls94pfJ-NchMLoFd9f4:b-drbcbb)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-26 22:03 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/348#-:-Ls952qY4_s7Dvmjj99D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-26 22:03 UTC, merged

2019-10-26 22:04 UTC, PlagueHO commented
Tagging @johlju - this is now through, so if there are any outstanding repos impacted by this then we'll need to prioritize fixing them. But I think they're mostly all done.

2019-10-28 19:47 UTC, X-Guardian commented
This is failing empty hashtables that are written `@{ }`, which is how the VSCode PowerShell text formatter formats them.

2019-10-28 20:22 UTC, SSvilen commented
The formatting is actually done by PSScriptAnalyzer.
There was a problem about it, which is fixed and I guess will be shipped in the next version of PSScriptAnalyter. [link](https://github.com/PowerShell/PSScriptAnalyzer/issues/1346)

2019-10-28 20:26 UTC, X-Guardian commented
Ok, couldn't we have held off on this change until PSScriptAnalyzer was fixed then?

2019-10-28 23:40 UTC, PlagueHO commented
@X-Guardian - that is my bad. It slipped my mind that the PSSA fix hadn't gone out yet (as it had been fixed - just not released).

Could we put a temporary fix in that accepts @{ } until the PSSA change is released?

2019-10-29 07:29 UTC, johlju commented
Yes let’s do that, because it can take a while before the new stable PSSA is shipped with VSCode PS extension. PSSA can be installed into the user module folder but all users might not do that, so let’s add an override for that.

2019-10-29 07:36 UTC, X-Guardian commented
The `ADServicePrincipalName` Resource in the `ActiveDirectoryDsc` module is failing this test on the following line:

```
Set-ADObject -Identity $spnAccount.DistinguishedName -Remove @{ ServicePrincipalName = $ServicePrincipalName }
```

How are you wanting this to be formatted?

2019-10-29 10:24 UTC, SSvilen commented
PR comes soon.
@X-Guardian  

The correct way would be: 

```powershell
Set-ADObject -Identity $spnAccount.DistinguishedName -Remove @{
    ServicePrincipalName = $ServicePrincipalName
}
```

2019-10-29 10:29 UTC, X-Guardian commented
Everyone happy with this? Personally, when it is a single key/value pair hashtable, the one line format looks better to me.

2019-10-29 14:30 UTC, SSvilen commented
I think we already had that discussion. But the [guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects) are clear about it. 

PR has been [opened](https://github.com/PowerShell/DscResource.Tests/pull/353).

2019-10-29 17:29 UTC, johlju commented
@X-Guardian Yep, We are happy with what @SSvilen said. Either according to how he showed, or add the hashtable to a variable and use that in the `Set-ADObject` call.

2019-10-29 17:29 UTC, johlju commented
@PlagueHO I will go through the modules that haven't been resolved in your list. Starting with those that will be released in a day or so.

2019-10-29 18:49 UTC, PlagueHO commented
Thanks @johlju - again, sorry about that - I got my wires crossed and thought that all the other resources had been completed.

2019-10-29 19:44 UTC, johlju commented
@PlagueHO No worries, my mistake! I was suppose to fix those last weekend. Totally forgot. But thanks to @SSvilen most are already fixed. I just sent in a PR to xBitlocker and I'm working on SqlServerDsc which is the only one left. It will not be released this time so there is no hurry, but I'm bored at a hotel today so I working on fixing that right now. 😄

2019-10-29 20:26 UTC, johlju commented
All modules should now be resolved or are pending a PR that will resolve the module.

Now we can start with the other PSSA rules @SSvilen has sent in a PR for. 😄

2019-10-29 20:32 UTC, PlagueHO commented
Thanks @johlju ! Glad you could be entertained at the hotel :grin:

2019-12-10 17:03 UTC, X-Guardian commented
xDnsServer is failing its meta-tests with several hashtable format errors that were missed for this. I've raised PR #119 to fix these, but the AppVeyor config for the repo is now not correct and is not running...

2019-12-10 17:11 UTC, X-Guardian commented
I take it back, the AppVeyor ran, it's just the licence/cla check that is still waiting. Can someone do a quick review of this if they have time?

2019-12-10 17:17 UTC, PlagueHO commented
@X-Guardian - yep. Tag me in it and I'll get it done.