Hashtable check - Fix for DSC composite resources
PowerShell/DscResource.Tests pull request #356
Opened 2019-11-15 20:02 UTC by SSvilen

#### Pull Request (PR) description
As mentions in this [PR](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/617), the DSC composite resources are also being parsed as hashtables. I have wrote a fix, that should remove the false/positives on those resources. 
I have tested it against few DSC Resources - I have not observed any false positives. 

#### This Pull Request (PR) fixes the following issues
[PR](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/617)

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2019-11-16 06:09 UTC, PlagueHO requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356)* status: all files reviewed, 1 unresolved discussion (waiting on @SSvilen)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1113 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/356#-Ltmp-Ur3KS6gWgnNo_L:-Ltmp-Ur3KS6gWgnNo_M:b-ouc1ax) ([raw file](https://github.com/powershell/dscresource.tests/blob/4c9a7db3b6661cfb7495efecd66447039a38be29/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113)):*
> ```PowerShell
> 
>             # Hashtable should start with '@{' and end with '}'
>             if (($hashtableLines[0] -notmatch '\s*@?{\r' -and $hashtableLines[0] -notmatch '\s*@?{$') -or
> ```

Is it worth adding a unit test to validate this condition?


<!-- Sent from Reviewable.io -->

2019-11-16 11:01 UTC, SSvilen reviewed
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1113 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/356#-Ltmp-Ur3KS6gWgnNo_L:-LtnrfnZ28W8UX6J9sww:bhdeith) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cefc0b4940521c871bf24c3540696153c0e949b/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it worth adding a unit test to validate this condition?
</blockquote></details>

I'm not sure how to simulate LF ending in a pester test.  I'll add a test for the composite resources check.


<!-- Sent from Reviewable.io -->

2019-11-25 15:54 UTC, mhendric commented
Hey @SSvilen and @PlagueHO , just wanted to check on the review status for this one. Not sure who owns the next action at the moment...

2019-11-25 22:27 UTC, SSvilen commented
I think @PlagueHO or @johlju  needs to review the change. @gaelcolas  already merged that change in the new DscResource.AnalyzerRules module.

2019-11-26 00:24 UTC, gaelcolas approved these changes
I'm ok with the change, but bear in mind this repository will be deprecated soon, use DscResource.AnalyzerRules and DscResource.Test (not yet released to gallery) instead.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356#-:-Lu_4RWq1LmOrt_nY8yM:bf6ozpv)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-11-26 00:25 UTC, gaelcolas approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356#-:-Lu_5Aza-4RGhC-wv2T-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2019-11-26 00:25 UTC, gaelcolas approved these changes
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1113 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/356#-Ltmp-Ur3KS6gWgnNo_L:-Lu_5Hx19roOJ9lqc3db:b2nhktp) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cefc0b4940521c871bf24c3540696153c0e949b/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113)):*
<details><summary><i>Previously, SSvilen (Svilen) wrote…</i></summary><blockquote>

I'm not sure how to simulate LF ending in a pester test.  I'll add a test for the composite resources check.
</blockquote></details>

OK.


<!-- Sent from Reviewable.io -->

2019-11-26 07:36 UTC, PlagueHO approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/356)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-11-26 07:36 UTC, merged